/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-12-05 09:11:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.project.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.MemberVO;
import java.util.ArrayList;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/project/member/../common/header.jsp", Long.valueOf(1579140940086L));
    _jspx_dependants.put("/project/member/../common/footer.jsp", Long.valueOf(1607155961039L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.MemberVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입 페이지 </title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/main.css\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/register.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"../js/httpRequest.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t//아이디 중복체크//\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#register_id\").on(\"keyup\",IDcheckup).on(\"change\",idCondition);\r\n");
      out.write("\t});\r\n");
      out.write("\t function idCondition(){\r\n");
      out.write("\t\tvar id = document.getElementById(\"register_id\").value;\r\n");
      out.write("\t\t//id가 4보다 작고 16보다 크면\r\n");
      out.write("\t\tif(id.length<4||id.length>16){\r\n");
      out.write("\t\t\tdocument.getElementById('register_idCheck').innerHTML='4자 이상, 16자 이하만 가능합니다. ';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(id.length>4||id.length<16){\r\n");
      out.write("\t\t\tdocument.getElementById('register_idCheck').innerHTML='사용가능 합니다.';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction IDcheckup(){\r\n");
      out.write("\t\tconsole.log($(\"#register_id\").val());\r\n");
      out.write("\t\tvar txt = $(\"#register_id\").val().trim(); //입력한 값을 가져와서 공백제거\r\n");
      out.write("\t\tvar params = \"id=\"+txt;\r\n");
      out.write("\t\t//idCheckup.jsp?id=testid\r\n");
      out.write("\t\tsendRequest(\"idCheckup.jsp\",params, IDcallback, \"GET\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction IDcallback(){\r\n");
      out.write("\t\t//통신완료&&정상페이지라면\r\n");
      out.write("\t\tif(xhr.readyState==4 && xhr.status==200){\r\n");
      out.write("\t\t\tvar msg = xhr.responseText.trim();\r\n");
      out.write("\t\t\tvar txt = $(\"#register_id\").val().trim();\r\n");
      out.write("\t\t\t//만약 응답이 true라면 p태그에 중복된 아이디입니다.\r\n");
      out.write("\t\t\tconsole.log(msg);\r\n");
      out.write("\t\t\tif(msg=='true'){\r\n");
      out.write("\t\t\t\t$(\"#register_idCheck\").html(\"중복된 아이디입니다.\").css(\"color\",\"red\").css(\"display\",\"inline\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//false면서 입력한 값이 null이 아니라면 '사용가능합니다. '\r\n");
      out.write("\t\t\telse if (msg=='false'&&txt.length!=0){\r\n");
      out.write("\t\t\t\t$(\"#register_idCheck\").html(\"사용가능합니다.\").css(\"color\",\"red\").css(\"display\",\"inline\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$(\"#register_idCheck\").html(\"잘못된 아이디입니다. \").css(\"color\",\"red\").css(\"display\",\"inline\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//이메일 중복체크//\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#register_email\").on(\"keyup\",emailCheckup);\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction emailCheckup(){\r\n");
      out.write("\t\tconsole.log($(\"#register_email\").val());\r\n");
      out.write("\t\tvar txt = $(\"#register_email\").val().trim();\r\n");
      out.write("\t\tvar params = \"email=\"+txt;\r\n");
      out.write("\t\tsendRequest(\"emailCheckup.jsp\",params, emailCallback, \"GET\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction emailCallback(){\r\n");
      out.write("\t\tif(xhr.readyState==4 && xhr.status==200){\r\n");
      out.write("\t\t\tvar msg = xhr.responseText.trim();\r\n");
      out.write("\t\t\tvar txt = $(\"#register_email\").val().trim();\r\n");
      out.write("\t\t\t//만약 응답이 true라면 p태그에 중복된 이메일입니다.\r\n");
      out.write("\t\t\t//false라면 사용 가능합니다.\r\n");
      out.write("\t\t\tif(msg=='true'){\r\n");
      out.write("\t\t\t\t$(\"#register_emailCheck\").html(\"중복된 이메일입니다.\").css(\"color\",\"red\").css(\"display\",\"inline\").css(\"font-size\",\"13px\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(msg=='false'&&txt.length!=0){\r\n");
      out.write("\t\t\t\t$(\"#register_emailCheck\").html(\"사용가능합니다.\").css(\"color\",\"red\").css(\"display\",\"inline\").css(\"font-size\",\"13px\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t//비밀번호&비밀번호확인 동일여부//\r\n");
      out.write("\tfunction isSame(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar pw = document.getElementById(\"register_pw\").value;\r\n");
      out.write("\t\tvar pwCheck = document.getElementById(\"register_pwCheck\").value;\r\n");
      out.write("\t\t//비밀번호 값이 8자 이상, 16글자 이하라면 ↓ 이렇게 문구 바꿔줘\r\n");
      out.write("\t\tif(pw.length<8||pw.length>16){\r\n");
      out.write("\t\t\tdocument.getElementById('register_pwlimit').innerHTML='비밀번호는 8자 이상, 16글자 이하만 가능합니다. ';\r\n");
      out.write("\t\t\tdocument.getElementById(\"register_pw\").value=document.getElementById(\"register_pwCheck\").value='';\r\n");
      out.write("\t\t\tdocument.getElementById('register_same').innerHTML='';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//비밀번호 값이 8자 이하, 16글자 이상이라면 ↓ 이렇게 문구 바꿔줘\r\n");
      out.write("\t\telse if(pw.length>8||pw.length<16){\r\n");
      out.write("\t\t\tdocument.getElementById('register_pwlimit').innerHTML='사용가능 합니다. ';\r\n");
      out.write("\t\t\tdocument.getElementById('register_same').innerHTML='';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.getElementById(\"register_pw\").value!=''&&document.getElementById(\"register_pwCheck\").value!=''){\r\n");
      out.write("\t\t\tif(document.getElementById(\"register_pw\").value==document.getElementById(\"register_pwCheck\").value){\r\n");
      out.write("\t\t\t\tdocument.getElementById('register_same').innerHTML='비밀번호가 일치합니다.';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tdocument.getElementById('register_same').innerHTML='비밀번호가 일치하지 않습니다.';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//다음주소api//\r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\tvar addressImg = document.getElementById(\"register_addressImg\");\r\n");
      out.write("\t\taddressImg.onclick=openKaKaoPostcode;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction openKaKaoPostcode(){\r\n");
      out.write("\t\t\tnew daum.Postcode({\r\n");
      out.write("\t\t\t\toncomplete:function(data){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"register_addNum\").value=data.zonecode;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"register_add1\").value=data.address;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}).open();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t//전체동의기능//\r\n");
      out.write("\tvar allck = document.getElementById(\"register_allAgree\");\r\n");
      out.write("\tallck.onclick = function(){\r\n");
      out.write("\t\t//name이 agree인 애들을 ck에 대입\r\n");
      out.write("\t\tvar ck = document.getElementsByName('register_agree');\r\n");
      out.write("\t\tfor(var i=0; i<ck.length; i++){\r\n");
      out.write("\t\t\tvar box = ck[i];\r\n");
      out.write("\t\t\tbox.checked = allck.checked;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t//회원약관 동의여부\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\t$(\"#register_button\").on(\"click\", checkAgree);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction checkAgree(){\r\n");
      out.write("\t\t//필수동의1\r\n");
      out.write("\t\tvar checked1 = document.getElementById(\"register_ck1\");\r\n");
      out.write("\t\t//필수동의2\r\n");
      out.write("\t\tvar checked2 = document.getElementById(\"register_ck2\");\r\n");
      out.write("\t\t//form ID\r\n");
      out.write("\t\tvar registerOK = document.getElementById(\"register_form\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//체크1,2가 체크되면 OK.jsp로 이동\r\n");
      out.write("\t\tif(checked1.checked&&checked2.checked){\r\n");
      out.write("\t\t\tconsole.log(\"OKOK\");\r\n");
      out.write("\t\t\tregisterOK.action=\"registerOk.jsp\";\r\n");
      out.write("\t\t\tregisterOK.method=\"get\";\r\n");
      out.write("\t\t\tregisterOK.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"약관을 동의하시오\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

   
    	//String homeURL = "http://192.168.0.4:8080/edgeliving/project";
    	String homeURL = "/edgeliving/project";
    	//String homeURL = "http://192.168.0.4:8080/edgeliving/project";
    	String WebURL = "/edgeliving";
    
    
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t\t<div class=\"header1\" >\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL);
      out.write("/index.jsp\"><img src=\"");
      out.print(WebURL );
      out.write("/semiImages/logo.png\" alt=\"logo.png\"  id=\"mainlogo\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header1\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<strong>인기검색어</strong> <a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=자크라디\" class=\"search_a\">자크라디</a> &nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=임페리얼\" class=\"search_a\">임페리얼 포셀린</a> &nbsp; \r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=보니타하우스\"\tclass=\"search_a\">보니타하우스</a> &nbsp;\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp\" id=\"search_form\" name=\"search_frm\" onsubmit=\"return checkSearch()\">\r\n");
      out.write("\t\t\t \t\t<input type=\"text\" value=\"\" name=\"search\" size=\"40\" id=\"header_search_text\"/>\r\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"검색\" />\r\n");
      out.write("\t\t\t \t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checkSearch(){\r\n");
      out.write("\t\t\tif(search_frm.search.value == \"\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t    alert(\"값을 입력해 주세요.\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t    search_frm.search.focus();\r\n");
      out.write("\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t  }else{\r\n");
      out.write("\t\t\t\t  return true;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t  \r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t");


		Object obj = session.getAttribute("vo");
		
		MemberVO mVO = (MemberVO)obj;
		//
		if(obj == null){
			
		 
		
		
      out.write("\r\n");
      out.write("\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">로그인</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/member/register.jsp\" class=\"header_a2\">회원가입</a> <a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");

		}else{
			
			if(mVO.getAuthority() < 99){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/logout.jsp\" class=\"header_a2\">로그아웃</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/myPage/myPage.jsp\"  class=\"header_a2\">마이페이지</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/mainpage/viewcart.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/checkout/orderlist.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

				
			}else{
				
      out.write("\r\n");
      out.write("\t\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/logout.jsp\" class=\"header_a2\">로그아웃</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/myPage/myPage.jsp\"  class=\"header_a2\">마이페이지</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/mainpage/viewcart.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/checkout/orderlist.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/admin/main.jsp\" class=\"header_a2\">관리자페이지</a>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

			}
		}
		
      out.write("\r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t\t\t<ul id=\"topMenu\">\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=0\" class=\"menu\" id=\"allCategory\">전체상품</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=1\" class=\"menu\" id=\"newProd\">신상품</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=2\" class=\"menu\" id=\"best50\">베스트40</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/brand/brand.jsp\" class=\"menu\" id=\"brand\">브랜드</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/board/review.jsp\" class=\"menu\" id =\"review\">생생후기</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"contents\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"register_path\">\r\n");
      out.write("\t<a href=\"index.jsp\">홈</a>>\r\n");
      out.write("\t<strong>회원가입</strong>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>회원가입</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h4>기본정보</h4>\r\n");
      out.write("<form action=\"registerOk.jsp\" id=\"register_form\">\r\n");
      out.write("<p class=\"register_ptag\"><img src=\"./image/star.gif\" alt=\"필수입력사항\" style=\"margin-left:90%;\"/>필수입력사항</p>\r\n");
      out.write("<div class=\"register_basicinfo\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"register_id\">\r\n");
      out.write("\t아이디<img src=\"./image/star.gif\" alt=\"아이디\" />\r\n");
      out.write("\t\t<input type=\"text\" name=\"register_id\" id=\"register_id\" style=\"margin-left:30px;\" maxlength=\"16\" onKeyup=\"this.value=this.value.replace(/[^a-z0-9]/g,'');\"/>\r\n");
      out.write("\t\t<p class=\"register_ptag\" id=\"register_idCheck\"> (영문소문자/숫자, 4~16자)</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"register_pw\">\r\n");
      out.write("\t비밀번호<img src=\"./image/star.gif\" alt=\"비밀번호\" />\r\n");
      out.write("\t\t<input type=\"password\" name=\"register_pw\" id=\"register_pw\" style=\"margin-left:15px;\" maxlength=\"16\"\r\n");
      out.write("\t\tonchange=\"isSame()\"/>\r\n");
      out.write("\t\t<p class=\"register_ptag\" id=\"register_pwlimit\">(8자~16자)</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"register_pwCheck\">\r\n");
      out.write("\t비밀번호 확인<img src=\"./image/star.gif\" alt=\"비밀번호 확인\" />\r\n");
      out.write("\t\t<input type=\"password\" name=\"register_pwCheck\" id=\"register_pwCheck\" style=\"margin-left:10px;\" maxlength=\"16\"\r\n");
      out.write("\t\tonchange=\"isSame()\"/>\r\n");
      out.write("\t\t<p id=\"register_same\" style=\"display:inline; color:red; font-size:13px;\"></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"register_name\">\r\n");
      out.write("\t이름<img src=\"./image/star.gif\" alt=\"이름\" />\r\n");
      out.write("\t\t<input type=\"text\" name=\"register_name\" id=\"register_name\" style=\"margin-left:30px;\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"register_address1\" style=\"border-bottom : 1px solid lightgray;\">\r\n");
      out.write("\t<div  class=\"register_address2\">\r\n");
      out.write("\t주소<img src=\"./image/star.gif\" alt=\"주소\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<input type=\"text\" name=\"register_addNum\" id=\"register_addNum\" style=\"width:120px;\"/>\r\n");
      out.write("\t\t<input type=\"button\" value=\"우편번호\" id=\"register_addressImg\"/>\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t<input type=\"text\" name=\"register_add1\" id=\"register_add1\" size=\"80px\"/> <p class=\"register_ptag\">기본주소</p>  <br /> <br />\r\n");
      out.write("\t\t<input type=\"text\" name=\"register_add2\" id=\"register_add2\" size=\"80px\"/> <p class=\"register_ptag\">상세주소</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"register_phone\">\r\n");
      out.write("\t휴대전화<img src=\"./image/star.gif\" alt=\"휴대전화\" />\r\n");
      out.write("\t\t<select name=\"register_number\" id=\"register_number\" style=\"margin-left:20px;\">\r\n");
      out.write("\t\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t<option value=\"016\">016</option>\r\n");
      out.write("\t\t</select> -\r\n");
      out.write("\t\t<input type=\"text\" name=\"register_pho\" id=\"register_pho\" style=\"width:100px\"  maxlength=\"4\">  -\r\n");
      out.write("\t\t<input type=\"text\" name=\"register_ne\" id=\"register_ne\" style=\"width:100px\" maxlength=\"4\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"register_email\">\r\n");
      out.write("\t이메일<img src=\"./image/star.gif\" alt=\"이메일\" />\r\n");
      out.write("\t<input type=\"text\" name=\"register_email\" id=\"register_email\" style=\"margin-left:35px;\"/>\r\n");
      out.write("\t<p id=\"register_emailCheck\"></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"register_gender\">\r\n");
      out.write("\t성별<img src=\"./image/star.gif\" alt=\"성별\" />\r\n");
      out.write("\t<input type=\"radio\" name=\"register_gender\" value =\"남\" id=\"register_man\" style=\"margin-left:50px;\" />남\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"register_gender\" value =\"여\" id=\"register_woman\" />여\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"register_dob\">\r\n");
      out.write("\t생년월일<img src=\"./image/star.gif\" alt=\"생년월일\" />\r\n");
      out.write("\t<input type=\"date\" name=\"register_datepicker\" id=\"register_datepicker\" placeholder=\"yyyy/mm/dd\"/>\r\n");
      out.write("\t<input type=\"radio\" name=\"register_yangum\" id=\"register_yang\" />양력\r\n");
      out.write("\t<input type=\"radio\" name=\"register_yangum\" id=\"register_um\" />음력\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h4>전체동의</h4>\r\n");
      out.write("<section class=\"register_agreebox\">\r\n");
      out.write("<input type=\"checkbox\" name=\"register_allAgree\" id=\"register_allAgree\" /> <b>이용약관 및 개인정보수집 및 이용, 쇼핑정보 수신(선택)에 모두 동의합니다.</b>\r\n");
      out.write("<article>\r\n");
      out.write("\t<h5>[필수] 이용약관 동의</h5>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<textarea name=\"\" id=\"\" cols=\"150\" rows=\"10\" disabled>\r\n");
      out.write("제1조(목적)\r\n");
      out.write("이 약관은 담소리빙(전자상거래 사업자)가 운영하는 담소리빙 몰(이하 “몰”이라 한다)에서 제공하는 인터넷 관련 서비스(이하 “서비스”라 한다)를 이용함에 있어 사이버 몰과 이용자의 권리․의무 및 책임사항을 규정함을 목적으로 합니다.\r\n");
      out.write("※「PC통신, 무선 등을 이용하는 전자상거래에 대해서도 그 성질에 반하지 않는 한 이 약관을 준용합니다.」\r\n");
      out.write("\r\n");
      out.write("제2조(정의)\r\n");
      out.write("① “몰”이란 담소리빙이 재화 또는 용역(이하 “재화 등”이라 함)을 이용자에게 제공하기 위하여 컴퓨터 등 정보통신설비를 이용하여 재화 등을 거래할 수 있도록 설정한 가상의 영업장을 말하며, 아울러 사이버몰을 운영하는 사업자의 의미로도 사용합니다.\r\n");
      out.write("② “이용자”란 “몰”에 접속하여 이 약관에 따라 “몰”이 제공하는 서비스를 받는 회원 및 비회원을 말합니다.\r\n");
      out.write("③ ‘회원’이라 함은 “몰”에 (삭제) 회원등록을 한 자로서, 계속적으로 “몰”이 제공하는 서비스를 이용할 수 있는 자를 말합니다.\r\n");
      out.write("④ ‘비회원’이라 함은 회원에 가입하지 않고 “몰”이 제공하는 서비스를 이용하는 자를 말합니다.\r\n");
      out.write("\r\n");
      out.write("제3조 (약관 등의 명시와 설명 및 개정)\r\n");
      out.write("① “몰”은 이 약관의 내용과 상호 및 대표자 성명, 영업소 소재지 주소(소비자의 불만을 처리할 수 있는 곳의 주소를 포함), 전화번호․모사전송번호․전자우편주소, 사업자등록번호, 통신판매업 신고번호, 개인정보보호책임자등을 이용자가 쉽게 알 수 있도록 00 사이버몰의 초기 서비스화면(전면)에 게시합니다. 다만, 약관의 내용은 이용자가 연결화면을 통하여 볼 수 있도록 할 수 있습니다.\r\n");
      out.write("② “몰은 이용자가 약관에 동의하기에 앞서 약관에 정하여져 있는 내용 중 청약철회․배송책임․환불조건 등과 같은 중요한 내용을 이용자가 이해할 수 있도록 별도의 연결화면 또는 팝업화면 등을 제공하여 이용자의 확인을 구하여야 합니다.\r\n");
      out.write("③ “몰”은 「전자상거래 등에서의 소비자보호에 관한 법률」, 「약관의 규제에 관한 법률」, 「전자문서 및 전자거래기본법」, 「전자금융거래법」, 「전자서명법」, 「정보통신망 이용촉진 및 정보보호 등에 관한 법률」, 「방문판매 등에 관한 법률」, 「소비자기본법」 등 관련 법을 위배하지 않는 범위에서 이 약관을 개정할 수 있습니다.\r\n");
      out.write("④ “몰”이 약관을 개정할 경우에는 적용일자 및 개정사유를 명시하여 현행약관과 함께 몰의 초기화면에 그 적용일자 7일 이전부터 적용일자 전일까지 공지합니다. 다만, 이용자에게 불리하게 약관내용을 변경하는 경우에는 최소한 30일 이상의 사전 유예기간을 두고 공지합니다. 이 경우 \"몰“은 개정 전 내용과 개정 후 내용을 명확하게 비교하여 이용자가 알기 쉽도록 표시합니다.\r\n");
      out.write("⑤ “몰”이 약관을 개정할 경우에는 그 개정약관은 그 적용일자 이후에 체결되는 계약에만 적용되고 그 이전에 이미 체결된 계약에 대해서는 개정 전의 약관조항이 그대로 적용됩니다. 다만 이미 계약을 체결한 이용자가 개정약관 조항의 적용을 받기를 원하는 뜻을 제3항에 의한 개정약관의 공지기간 내에 “몰”에 송신하여 “몰”의 동의를 받은 경우에는 개정약관 조항이 적용됩니다.\r\n");
      out.write("⑥ 이 약관에서 정하지 아니한 사항과 이 약관의 해석에 관하여는 전자상거래 등에서의 소비자보호에 관한 법률, 약관의 규제 등에 관한 법률, 공정거래위원회가 정하는 전자상거래 등에서의 소비자 보호지침 및 관계법령 또는 상관례에 따릅니다.\r\n");
      out.write("\r\n");
      out.write("제4조(서비스의 제공 및 변경)\r\n");
      out.write("① “몰”은 다음과 같은 업무를 수행합니다.\r\n");
      out.write("  1. 재화 또는 용역에 대한 정보 제공 및 구매계약의 체결\r\n");
      out.write("  2. 구매계약이 체결된 재화 또는 용역의 배송\r\n");
      out.write("  3. 기타 “몰”이 정하는 업무\r\n");
      out.write("② “몰”은 재화 또는 용역의 품절 또는 기술적 사양의 변경 등의 경우에는 장차 체결되는 계약에 의해 제공할 재화 또는 용역의 내용을 변경할 수 있습니다. 이 경우에는 변경된 재화 또는 용역의 내용 및 제공일자를 명시하여 현재의 재화 또는 용역의 내용을 게시한 곳에 즉시 공지합니다.\r\n");
      out.write("③ “몰”이 제공하기로 이용자와 계약을 체결한 서비스의 내용을 재화등의 품절 또는 기술적 사양의 변경 등의 사유로 변경할 경우에는 그 사유를 이용자에게 통지 가능한 주소로 즉시 통지합니다.\r\n");
      out.write("④ 전항의 경우 “몰”은 이로 인하여 이용자가 입은 손해를 배상합니다. 다만, “몰”이 고의 또는 과실이 없음을 입증하는 경우에는 그러하지 아니합니다.\r\n");
      out.write("\r\n");
      out.write("제5조(서비스의 중단)\r\n");
      out.write("① “몰”은 컴퓨터 등 정보통신설비의 보수점검․교체 및 고장, 통신의 두절 등의 사유가 발생한 경우에는 서비스의 제공을 일시적으로 중단할 수 있습니다.\r\n");
      out.write("② “몰”은 제1항의 사유로 서비스의 제공이 일시적으로 중단됨으로 인하여 이용자 또는 제3자가 입은 손해에 대하여 배상합니다. 단, “몰”이 고의 또는 과실이 없음을 입증하는 경우에는 그러하지 아니합니다.\r\n");
      out.write("③ 사업종목의 전환, 사업의 포기, 업체 간의 통합 등의 이유로 서비스를 제공할 수 없게 되는 경우에는 “몰”은 제8조에 정한 방법으로 이용자에게 통지하고 당초 “몰”에서 제시한 조건에 따라 소비자에게 보상합니다. 다만, “몰”이 보상기준 등을 고지하지 아니한 경우에는 이용자들의 마일리지 또는 적립금 등을 “몰”에서 통용되는 통화가치에 상응하는 현물 또는 현금으로 이용자에게 지급합니다.\r\n");
      out.write("\r\n");
      out.write("제6조(회원가입)\r\n");
      out.write("① 이용자는 “몰”이 정한 가입 양식에 따라 회원정보를 기입한 후 이 약관에 동의한다는 의사표시를 함으로서 회원가입을 신청합니다.\r\n");
      out.write("② “몰”은 제1항과 같이 회원으로 가입할 것을 신청한 이용자 중 다음 각 호에 해당하지 않는 한 회원으로 등록합니다.\r\n");
      out.write("  1. 가입신청자가 이 약관 제7조제3항에 의하여 이전에 회원자격을 상실한 적이 있는 경우, 다만 제7조제3항에 의한 회원자격 상실 후 3년이 경과한 자로서 “몰”의 회원재가입 승낙을 얻은 경우에는 예외로 한다.\r\n");
      out.write("  2. 등록 내용에 허위, 기재누락, 오기가 있는 경우\r\n");
      out.write("  3. 기타 회원으로 등록하는 것이 “몰”의 기술상 현저히 지장이 있다고 판단되는 경우\r\n");
      out.write("③ 회원가입계약의 성립 시기는 “몰”의 승낙이 회원에게 도달한 시점으로 합니다.\r\n");
      out.write("④ 회원은 회원가입 시 등록한 사항에 변경이 있는 경우, 상당한 기간 이내에 “몰”에 대하여 회원정보 수정 등의 방법으로 그 변경사항을 알려야 합니다.\r\n");
      out.write("\r\n");
      out.write("제7조(회원 탈퇴 및 자격 상실 등)\r\n");
      out.write("① 회원은 “몰”에 언제든지 탈퇴를 요청할 수 있으며 “몰”은 즉시 회원탈퇴를 처리합니다.\r\n");
      out.write("② 회원이 다음 각 호의 사유에 해당하는 경우, “몰”은 회원자격을 제한 및 정지시킬 수 있습니다.\r\n");
      out.write("  1. 가입 신청 시에 허위 내용을 등록한 경우\r\n");
      out.write("  2. “몰”을 이용하여 구입한 재화 등의 대금, 기타 “몰”이용에 관련하여 회원이 부담하는 채무를 기일에 지급하지 않는 경우\r\n");
      out.write("  3. 다른 사람의 “몰” 이용을 방해하거나 그 정보를 도용하는 등 전자상거래 질서를 위협하는 경우\r\n");
      out.write("  4. “몰”을 이용하여 법령 또는 이 약관이 금지하거나 공서양속에 반하는 행위를 하는 경우\r\n");
      out.write("③ “몰”이 회원 자격을 제한․정지 시킨 후, 동일한 행위가 2회 이상 반복되거나 30일 이내에 그 사유가 시정되지 아니하는 경우 “몰”은 회원자격을 상실시킬 수 있습니다.\r\n");
      out.write("④ “몰”이 회원자격을 상실시키는 경우에는 회원등록을 말소합니다. 이 경우 회원에게 이를 통지하고, 회원등록 말소 전에 최소한 30일 이상의 기간을 정하여 소명할 기회를 부여합니다.\r\n");
      out.write("\r\n");
      out.write("제8조(회원에 대한 통지)\r\n");
      out.write("① “몰”이 회원에 대한 통지를 하는 경우, 회원이 “몰”과 미리 약정하여 지정한 전자우편 주소로 할 수 있습니다.\r\n");
      out.write("② “몰”은 불특정다수 회원에 대한 통지의 경우 1주일이상 “몰” 게시판에 게시함으로서 개별 통지에 갈음할 수 있습니다. 다만, 회원 본인의 거래와 관련하여 중대한 영향을 미치는 사항에 대하여는 개별통지를 합니다.\r\n");
      out.write("\r\n");
      out.write("제9조(구매신청)\r\n");
      out.write("① “몰”이용자는 “몰”상에서 다음 또는 이와 유사한 방법에 의하여 구매를 신청하며, “몰”은 이용자가 구매신청을 함에 있어서 다음의 각 내용을 알기 쉽게 제공하여야 합니다. (삭제)\r\n");
      out.write("  1. 재화 등의 검색 및 선택\r\n");
      out.write("  2. 받는 사람의 성명, 주소, 전화번호, 전자우편주소(또는 이동전화번호) 등의 입력\r\n");
      out.write("  3. 약관내용, 청약철회권이 제한되는 서비스, 배송료․설치비 등의 비용부담과 관련한 내용에 대한 확인\r\n");
      out.write("  4. 이 약관에 동의하고 위 3.호의 사항을 확인하거나 거부하는 표시(예, 마우스 클릭)\r\n");
      out.write("  5. 재화등의 구매신청 및 이에 관한 확인 또는 “몰”의 확인에 대한 동의\r\n");
      out.write("  6. 결제방법의 선택\r\n");
      out.write("② “몰”이 제3자에게 구매자 개인정보를 제공•위탁할 필요가 있는 경우 실제 구매신청 시 구매자의 동의를 받아야 하며, 회원가입 시 미리 포괄적으로 동의를 받지 않습니다. 이 때 “몰”은 제공되는 개인정보 항목, 제공받는 자, 제공받는 자의 개인정보 이용 목적 및 보유‧이용 기간 등을 구매자에게 명시하여야 합니다. 다만 「정보통신망이용촉진 및 정보보호 등에 관한 법률」 제25조 제1항에 의한 개인정보 처리위탁의 경우 등 관련 법령에 달리 정함이 있는 경우에는 그에 따릅니다.\r\n");
      out.write("\r\n");
      out.write("제10조 (계약의 성립)\r\n");
      out.write("① “몰”은 제9조와 같은 구매신청에 대하여 다음 각 호에 해당하면 승낙하지 않을 수 있습니다. 다만, 미성년자와 계약을 체결하는 경우에는 법정대리인의 동의를 얻지 못하면 미성년자 본인 또는 법정대리인이 계약을 취소할 수 있다는 내용을 고지하여야 합니다.\r\n");
      out.write("  1. 신청 내용에 허위, 기재누락, 오기가 있는 경우\r\n");
      out.write("  2. 미성년자가 담배, 주류 등 청소년보호법에서 금지하는 재화 및 용역을 구매하는 경우\r\n");
      out.write("  3. 기타 구매신청에 승낙하는 것이 “몰” 기술상 현저히 지장이 있다고 판단하는 경우\r\n");
      out.write("② “몰”의 승낙이 제12조제1항의 수신확인통지형태로 이용자에게 도달한 시점에 계약이 성립한 것으로 봅니다.\r\n");
      out.write("③ “몰”의 승낙의 의사표시에는 이용자의 구매 신청에 대한 확인 및 판매가능 여부, 구매신청의 정정 취소 등에 관한 정보 등을 포함하여야 합니다.\r\n");
      out.write("\r\n");
      out.write("제11조(지급방법)\r\n");
      out.write("“몰”에서 구매한 재화 또는 용역에 대한 대금지급방법은 다음 각 호의 방법중 가용한 방법으로 할 수 있습니다. 단, “몰”은 이용자의 지급방법에 대하여 재화 등의 대금에 어떠한 명목의 수수료도 추가하여 징수할 수 없습니다.\r\n");
      out.write("1. 폰뱅킹, 인터넷뱅킹, 메일 뱅킹 등의 각종 계좌이체\r\n");
      out.write("2. 선불카드, 직불카드, 신용카드 등의 각종 카드 결제\r\n");
      out.write("3. 온라인무통장입금\r\n");
      out.write("4. 전자화폐에 의한 결제\r\n");
      out.write("5. 수령 시 대금지급\r\n");
      out.write("6. 마일리지 등 “몰”이 지급한 포인트에 의한 결제\r\n");
      out.write("7. “몰”과 계약을 맺었거나 “몰”이 인정한 상품권에 의한 결제\r\n");
      out.write("8. 기타 전자적 지급 방법에 의한 대금 지급 등\r\n");
      out.write("\r\n");
      out.write("제12조(수신확인통지․구매신청 변경 및 취소)\r\n");
      out.write("① “몰”은 이용자의 구매신청이 있는 경우 이용자에게 수신확인통지를 합니다.\r\n");
      out.write("② 수신확인통지를 받은 이용자는 의사표시의 불일치 등이 있는 경우에는 수신확인통지를 받은 후 즉시 구매신청 변경 및 취소를 요청할 수 있고 “몰”은 배송 전에 이용자의 요청이 있는 경우에는 지체 없이 그 요청에 따라 처리하여야 합니다. 다만 이미 대금을 지불한 경우에는 제15조의 청약철회 등에 관한 규정에 따릅니다.\r\n");
      out.write("\r\n");
      out.write("제13조(재화 등의 공급)\r\n");
      out.write("① “몰”은 이용자와 재화 등의 공급시기에 관하여 별도의 약정이 없는 이상, 이용자가 청약을 한 날부터 7일 이내에 재화 등을 배송할 수 있도록 주문제작, 포장 등 기타의 필요한 조치를 취합니다. 다만, “몰”이 이미 재화 등의 대금의 전부 또는 일부를 받은 경우에는 대금의 전부 또는 일부를 받은 날부터 3영업일 이내에 조치를 취합니다. 이때 “몰”은 이용자가 재화 등의 공급 절차 및 진행 사항을 확인할 수 있도록 적절한 조치를 합니다.\r\n");
      out.write("② “몰”은 이용자가 구매한 재화에 대해 배송수단, 수단별 배송비용 부담자, 수단별 배송기간 등을 명시합니다. 만약 “몰”이 약정 배송기간을 초과한 경우에는 그로 인한 이용자의 손해를 배상하여야 합니다. 다만 “몰”이 고의․과실이 없음을 입증한 경우에는 그러하지 아니합니다.\r\n");
      out.write("\r\n");
      out.write("제14조(환급)\r\n");
      out.write("“몰”은 이용자가 구매신청한 재화 등이 품절 등의 사유로 인도 또는 제공을 할 수 없을 때에는 지체 없이 그 사유를 이용자에게 통지하고 사전에 재화 등의 대금을 받은 경우에는 대금을 받은 날부터 3영업일 이내에 환급하거나 환급에 필요한 조치를 취합니다.\r\n");
      out.write("\r\n");
      out.write("제15조(청약철회 등)\r\n");
      out.write("① “몰”과 재화등의 구매에 관한 계약을 체결한 이용자는 「전자상거래 등에서의 소비자보호에 관한 법률」 제13조 제2항에 따른 계약내용에 관한 서면을 받은 날(그 서면을 받은 때보다 재화 등의 공급이 늦게 이루어진 경우에는 재화 등을 공급받거나 재화 등의 공급이 시작된 날을 말합니다)부터 7일 이내에는 청약의 철회를 할 수 있습니다. 다만, 청약철회에 관하여 「전자상거래 등에서의 소비자보호에 관한 법률」에 달리 정함이 있는 경우에는 동 법 규정에 따릅니다.\r\n");
      out.write("② 이용자는 재화 등을 배송 받은 경우 다음 각 호의 1에 해당하는 경우에는 반품 및 교환을 할 수 없습니다.\r\n");
      out.write("  1. 이용자에게 책임 있는 사유로 재화 등이 멸실 또는 훼손된 경우(다만, 재화 등의 내용을 확인하기 위하여 포장 등을 훼손한 경우에는 청약철회를 할 수 있습니다)\r\n");
      out.write("  2. 이용자의 사용 또는 일부 소비에 의하여 재화 등의 가치가 현저히 감소한 경우\r\n");
      out.write("  3. 시간의 경과에 의하여 재판매가 곤란할 정도로 재화등의 가치가 현저히 감소한 경우\r\n");
      out.write("  4. 같은 성능을 지닌 재화 등으로 복제가 가능한 경우 그 원본인 재화 등의 포장을 훼손한 경우\r\n");
      out.write("③ 제2항제2호 내지 제4호의 경우에 “몰”이 사전에 청약철회 등이 제한되는 사실을 소비자가 쉽게 알 수 있는 곳에 명기하거나 시용상품을 제공하는 등의 조치를 하지 않았다면 이용자의 청약철회 등이 제한되지 않습니다.\r\n");
      out.write("④ 이용자는 제1항 및 제2항의 규정에 불구하고 재화 등의 내용이 표시•광고 내용과 다르거나 계약내용과 다르게 이행된 때에는 당해 재화 등을 공급받은 날부터 3월 이내, 그 사실을 안 날 또는 알 수 있었던 날부터 30일 이내에 청약철회 등을 할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("제16조(청약철회 등의 효과)\r\n");
      out.write("① “몰”은 이용자로부터 재화 등을 반환받은 경우 3영업일 이내에 이미 지급받은 재화 등의 대금을 환급합니다. 이 경우 “몰”이 이용자에게 재화등의 환급을 지연한때에는 그 지연기간에 대하여 「전자상거래 등에서의 소비자보호에 관한 법률 시행령」제21조의2에서 정하는 지연이자율(괄호 부분 삭제)을 곱하여 산정한 지연이자를 지급합니다.\r\n");
      out.write("② “몰”은 위 대금을 환급함에 있어서 이용자가 신용카드 또는 전자화폐 등의 결제수단으로 재화 등의 대금을 지급한 때에는 지체 없이 당해 결제수단을 제공한 사업자로 하여금 재화 등의 대금의 청구를 정지 또는 취소하도록 요청합니다.\r\n");
      out.write("③ 청약철회 등의 경우 공급받은 재화 등의 반환에 필요한 비용은 이용자가 부담합니다. “몰”은 이용자에게 청약철회 등을 이유로 위약금 또는 손해배상을 청구하지 않습니다. 다만 재화 등의 내용이 표시•광고 내용과 다르거나 계약내용과 다르게 이행되어 청약철회 등을 하는 경우 재화 등의 반환에 필요한 비용은 “몰”이 부담합니다.\r\n");
      out.write("④ 이용자가 재화 등을 제공받을 때 발송비를 부담한 경우에 “몰”은 청약철회 시 그 비용을 누가 부담하는지를 이용자가 알기 쉽도록 명확하게 표시합니다.\r\n");
      out.write("\r\n");
      out.write("제17조(개인정보보호)\r\n");
      out.write("① “몰”은 이용자의 개인정보 수집시 서비스제공을 위하여 필요한 범위에서 최소한의 개인정보를 수집합니다.\r\n");
      out.write("② “몰”은 회원가입시 구매계약이행에 필요한 정보를 미리 수집하지 않습니다. 다만, 관련 법령상 의무이행을 위하여 구매계약 이전에 본인확인이 필요한 경우로서 최소한의 특정 개인정보를 수집하는 경우에는 그러하지 아니합니다.\r\n");
      out.write("③ “몰”은 이용자의 개인정보를 수집•이용하는 때에는 당해 이용자에게 그 목적을 고지하고 동의를 받습니다.\r\n");
      out.write("④ “몰”은 수집된 개인정보를 목적외의 용도로 이용할 수 없으며, 새로운 이용목적이 발생한 경우 또는 제3자에게 제공하는 경우에는 이용•제공단계에서 당해 이용자에게 그 목적을 고지하고 동의를 받습니다. 다만, 관련 법령에 달리 정함이 있는 경우에는 예외로 합니다.\r\n");
      out.write("⑤ “몰”이 제2항과 제3항에 의해 이용자의 동의를 받아야 하는 경우에는 개인정보보호 책임자의 신원(소속, 성명 및 전화번호, 기타 연락처), 정보의 수집목적 및 이용목적, 제3자에 대한 정보제공 관련사항(제공받은자, 제공목적 및 제공할 정보의 내용) 등 「정보통신망 이용촉진 및 정보보호 등에 관한 법률」 제22조제2항이 규정한 사항을 미리 명시하거나 고지해야 하며 이용자는 언제든지 이 동의를 철회할 수 있습니다.\r\n");
      out.write("⑥ 이용자는 언제든지 “몰”이 가지고 있는 자신의 개인정보에 대해 열람 및 오류정정을 요구할 수 있으며 “몰”은 이에 대해 지체 없이 필요한 조치를 취할 의무를 집니다. 이용자가 오류의 정정을 요구한 경우에는 “몰”은 그 오류를 정정할 때까지 당해 개인정보를 이용하지 않습니다.\r\n");
      out.write("⑦ “몰”은 개인정보 보호를 위하여 이용자의 개인정보를 처리하는 자를 최소한으로 제한하여야 하며 신용카드, 은행계좌 등을 포함한 이용자의 개인정보의 분실, 도난, 유출, 동의 없는 제3자 제공, 변조 등으로 인한 이용자의 손해에 대하여 모든 책임을 집니다.\r\n");
      out.write("⑧ “몰” 또는 그로부터 개인정보를 제공받은 제3자는 개인정보의 수집목적 또는 제공받은 목적을 달성한 때에는 당해 개인정보를 지체 없이 파기합니다.\r\n");
      out.write("⑨ “몰”은 개인정보의 수집•이용•제공에 관한 동의란을 미리 선택한 것으로 설정해두지 않습니다. 또한 개인정보의 수집•이용•제공에 관한 이용자의 동의거절시 제한되는 서비스를 구체적으로 명시하고, 필수수집항목이 아닌 개인정보의 수집•이용•제공에 관한 이용자의 동의 거절을 이유로 회원가입 등 서비스 제공을 제한하거나 거절하지 않습니다.\r\n");
      out.write("\r\n");
      out.write("제18조(“몰“의 의무)\r\n");
      out.write("① “몰”은 법령과 이 약관이 금지하거나 공서양속에 반하는 행위를 하지 않으며 이 약관이 정하는 바에 따라 지속적이고, 안정적으로 재화․용역을 제공하는데 최선을 다하여야 합니다.\r\n");
      out.write("② “몰”은 이용자가 안전하게 인터넷 서비스를 이용할 수 있도록 이용자의 개인정보(신용정보 포함)보호를 위한 보안 시스템을 갖추어야 합니다.\r\n");
      out.write("③ “몰”이 상품이나 용역에 대하여 「표시․광고의 공정화에 관한 법률」 제3조 소정의 부당한 표시․광고행위를 함으로써 이용자가 손해를 입은 때에는 이를 배상할 책임을 집니다.\r\n");
      out.write("④ “몰”은 이용자가 원하지 않는 영리목적의 광고성 전자우편을 발송하지 않습니다.\r\n");
      out.write("\r\n");
      out.write("제19조(회원의 ID 및 비밀번호에 대한 의무)\r\n");
      out.write("① 제17조의 경우를 제외한 ID와 비밀번호에 관한 관리책임은 회원에게 있습니다.\r\n");
      out.write("② 회원은 자신의 ID 및 비밀번호를 제3자에게 이용하게 해서는 안됩니다.\r\n");
      out.write("③ 회원이 자신의 ID 및 비밀번호를 도난당하거나 제3자가 사용하고 있음을 인지한 경우에는 바로 “몰”에 통보하고 “몰”의 안내가 있는 경우에는 그에 따라야 합니다.\r\n");
      out.write("\r\n");
      out.write("제20조(이용자의 의무)\r\n");
      out.write("이용자는 다음 행위를 하여서는 안 됩니다.\r\n");
      out.write("1. 신청 또는 변경시 허위 내용의 등록\r\n");
      out.write("2. 타인의 정보 도용\r\n");
      out.write("3. “몰”에 게시된 정보의 변경\r\n");
      out.write("4. “몰”이 정한 정보 이외의 정보(컴퓨터 프로그램 등) 등의 송신 또는 게시\r\n");
      out.write("5. “몰” 기타 제3자의 저작권 등 지적재산권에 대한 침해\r\n");
      out.write("6. “몰” 기타 제3자의 명예를 손상시키거나 업무를 방해하는 행위\r\n");
      out.write("7. 외설 또는 폭력적인 메시지, 화상, 음성, 기타 공서양속에 반하는 정보를 몰에 공개 또는 게시하는 행위\r\n");
      out.write("\r\n");
      out.write("제21조(연결“몰”과 피연결“몰” 간의 관계)\r\n");
      out.write("① 상위 “몰”과 하위 “몰”이 하이퍼링크(예: 하이퍼링크의 대상에는 문자, 그림 및 동화상 등이 포함됨)방식 등으로 연결된 경우, 전자를 연결 “몰”(웹 사이트)이라고 하고 후자를 피연결 “몰”(웹사이트)이라고 합니다.\r\n");
      out.write("② 연결“몰”은 피연결“몰”이 독자적으로 제공하는 재화 등에 의하여 이용자와 행하는 거래에 대해서 보증 책임을 지지 않는다는 뜻을 연결“몰”의 초기화면 또는 연결되는 시점의 팝업화면으로 명시한 경우에는 그 거래에 대한 보증 책임을 지지 않습니다.\r\n");
      out.write("\r\n");
      out.write("제22조(저작권의 귀속 및 이용제한)\r\n");
      out.write("① “몰“이 작성한 저작물에 대한 저작권 기타 지적재산권은 ”몰“에 귀속합니다.\r\n");
      out.write("② 이용자는 “몰”을 이용함으로써 얻은 정보 중 “몰”에게 지적재산권이 귀속된 정보를 “몰”의 사전 승낙 없이 복제, 송신, 출판, 배포, 방송 기타 방법에 의하여 영리목적으로 이용하거나 제3자에게 이용하게 하여서는 안됩니다.\r\n");
      out.write("③ “몰”은 약정에 따라 이용자에게 귀속된 저작권을 사용하는 경우 당해 이용자에게 통보하여야 합니다.\r\n");
      out.write("\r\n");
      out.write("제23조(분쟁해결)\r\n");
      out.write("① “몰”은 이용자가 제기하는 정당한 의견이나 불만을 반영하고 그 피해를 보상처리하기 위하여 피해보상처리기구를 설치․운영합니다.\r\n");
      out.write("② “몰”은 이용자로부터 제출되는 불만사항 및 의견은 우선적으로 그 사항을 처리합니다. 다만, 신속한 처리가 곤란한 경우에는 이용자에게 그 사유와 처리일정을 즉시 통보해 드립니다.\r\n");
      out.write("③ “몰”과 이용자 간에 발생한 전자상거래 분쟁과 관련하여 이용자의 피해구제신청이 있는 경우에는 공정거래위원회 또는 시•도지사가 의뢰하는 분쟁조정기관의 조정에 따를 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("제24조(재판권 및 준거법)\r\n");
      out.write("① “몰”과 이용자 간에 발생한 전자상거래 분쟁에 관한 소송은 제소 당시의 이용자의 주소에 의하고, 주소가 없는 경우에는 거소를 관할하는 지방법원의 전속관할로 합니다. 다만, 제소 당시 이용자의 주소 또는 거소가 분명하지 않거나 외국 거주자의 경우에는 민사소송법상의 관할법원에 제기합니다.\r\n");
      out.write("② “몰”과 이용자 간에 제기된 전자상거래 소송에는 한국법을 적용합니다.\r\n");
      out.write("\r\n");
      out.write("부 칙(시행일) 이 약관은 년 월 일부터 시행합니다.\r\n");
      out.write("\t\t</textarea>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"register_txt\">이용약관에 동의하십니까? <input type=\"checkbox\" name=\"register_agree\" id=\"register_ck1\" />동의함</div>\r\n");
      out.write("</article>\r\n");
      out.write("\t<article>\r\n");
      out.write("\t\t<h5>[필수] 개인정보 수집 및 이용 동의</h5>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<textarea name=\"\" id=\"\" cols=\"150\" rows=\"10\" disabled>\r\n");
      out.write("** 본 양식은 쇼핑몰 운영에 도움을 드리고자 샘플로 제공되는 서식으로 쇼핑몰 운영형태에 따른 수정이 필요합니다. 쇼핑몰에 적용하시기 전, 쇼핑몰 운영 사항 등을 확인하시고 적절한 내용을 반영하여 사용하시기 바랍니다. **\r\n");
      out.write("\r\n");
      out.write("1. 개인정보 수집목적 및 이용목적\r\n");
      out.write("\r\n");
      out.write("가. 서비스 제공에 관한 계약 이행 및 서비스 제공에 따른 요금정산\r\n");
      out.write("\r\n");
      out.write("콘텐츠 제공 , 구매 및 요금 결제 , 물품배송 또는 청구지 등 발송 , 금융거래 본인 인증 및 금융 서비스\r\n");
      out.write("\r\n");
      out.write("나. 회원 관리\r\n");
      out.write("\r\n");
      out.write("회원제 서비스 이용에 따른 본인확인 , 개인 식별 , 불량회원의 부정 이용 방지와 비인가 사용 방지 , 가입 의사 확인 , 연령확인 , 만14세 미만 아동 개인정보 수집 시 법정 대리인 동의여부 확인, 불만처리 등 민원처리 , 고지사항 전달\r\n");
      out.write("\r\n");
      out.write("2. 수집하는 개인정보 항목 : 이름 , 생년월일 , 성별 , 로그인ID , 비밀번호 , 자택 전화번호 , 휴대전화번호 , 이메일 , 14세미만 가입자의 경우 법정대리인의 정보\r\n");
      out.write("\r\n");
      out.write("3. 개인정보의 보유기간 및 이용기간\r\n");
      out.write("\r\n");
      out.write("원칙적으로, 개인정보 수집 및 이용목적이 달성된 후에는 해당 정보를 지체 없이 파기합니다. 단, 다음의 정보에 대해서는 아래의 이유로 명시한 기간 동안 보존합니다.\r\n");
      out.write("\r\n");
      out.write("가. 회사 내부 방침에 의한 정보 보유 사유\r\n");
      out.write("\r\n");
      out.write("o 부정거래 방지 및 쇼핑몰 운영방침에 따른 보관 : OO년\r\n");
      out.write("\r\n");
      out.write("나. 관련 법령에 의한 정보보유 사유\r\n");
      out.write("\r\n");
      out.write("o 계약 또는 청약철회 등에 관한 기록\r\n");
      out.write("\r\n");
      out.write("-보존이유 : 전자상거래등에서의소비자보호에관한법률\r\n");
      out.write("\r\n");
      out.write("-보존기간 : 5년\r\n");
      out.write("\r\n");
      out.write("o 대금 결제 및 재화 등의 공급에 관한 기록\r\n");
      out.write("\r\n");
      out.write("-보존이유: 전자상거래등에서의소비자보호에관한법률\r\n");
      out.write("\r\n");
      out.write("-보존기간 : 5년 \r\n");
      out.write("\r\n");
      out.write("o 소비자 불만 또는 분쟁처리에 관한 기록\r\n");
      out.write("\r\n");
      out.write("-보존이유 : 전자상거래등에서의소비자보호에관한법률\r\n");
      out.write("\r\n");
      out.write("-보존기간 : 3년 \r\n");
      out.write("\r\n");
      out.write("o 로그 기록 \r\n");
      out.write("\r\n");
      out.write("-보존이유: 통신비밀보호법\r\n");
      out.write("\r\n");
      out.write("-보존기간 : 3개월\r\n");
      out.write("\r\n");
      out.write("※ 동의를 거부할 수 있으나 거부시 회원 가입이 불가능합니다.\r\n");
      out.write("\t\t\t</textarea>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"register_txt\">개인정보 수집 및 이용에 동의하십니까? <input type=\"checkbox\" name=\"register_agree\" id=\"register_ck2\" />동의함</div>\r\n");
      out.write("\t</article>\r\n");
      out.write("\t<article>\r\n");
      out.write("\t\t<h5>[선택] 개인정보 처리 위탁 동의</h5>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<textarea name=\"\" id=\"\" cols=\"150\" rows=\"10\" disabled>\r\n");
      out.write("아래 내용의 동의 여부는 회원가입에 영향을 미치지 않습니다. 단, 동의 거부시 서비스 이용에 제한이 있을 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("- 위탁받는 자(수탁업체) : 사방넷,CJ대한통운\r\n");
      out.write("\r\n");
      out.write("- 위탁업무의 내용: 당사에서 수집한 개인정보를 사방넷에 위탁하여 주문정보(주문자,수령인,연락처,주소 등)를 배송 및 반품/교환 등의 서비스 제공 목적으로 사용한다.\r\n");
      out.write("CJ대한통운은 사방넷에서 수집된 주문정보를 입력하며 수집된 정보는 배송과 배송조회 등의 고객 편의를 위해 사용됩니다.\r\n");
      out.write("\t\t\t</textarea>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"register_txt\">개인정보 처리 위탁에 동의하십니까? <input type=\"checkbox\" name=\"register_agree\" id=\"\" />동의함</div>\r\n");
      out.write("\t</article>\r\n");
      out.write("\t<article>\r\n");
      out.write("\t\t<h5>[선택] 쇼핑정보 수신 동의</h5>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<textarea name=\"\" id=\"\" cols=\"150\" rows=\"10\" disabled>\r\n");
      out.write("할인쿠폰 및 혜택, 이벤트, 신상품 소식 등 쇼핑몰에서 제공하는 유익한 쇼핑정보를 SMS와 이메일로 받아보실 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("단, 주문/거래 정보 및 주요 정책과 관련된 내용은 수신동의 여부와 관계없이 발송됩니다.\r\n");
      out.write("\r\n");
      out.write("선택 약관에 동의하지 않으셔도 회원가입은 가능하며, 회원가입 후 회원정보수정 페이지에서 언제든지 수신여부를 변경하실 수 있습니다.\r\n");
      out.write("\t\t\t</textarea>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"register_txt\">\r\n");
      out.write("\t\tSMS 수신을 동의하십니까? <input type=\"checkbox\" name=\"register_agree\" id=\"\" />동의함 <br />\r\n");
      out.write("\t\t이메일 수신을 동의하십니까? <input type=\"checkbox\" name=\"register_agree\" id=\"\" />동의함 \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</article>\r\n");
      out.write("</section>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<input type=\"button\" id =\"register_button\"value=\"회원가입\" style=\"margin-left:50%; background:white; width:100px; height:50px; border-radius:15px;\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("    \t");
 String WebURL2 = "/edgeliving";
      out.write("\r\n");
      out.write("    \t\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 고객센터</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"> 031-904-8072 </div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t<p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 카카오톡 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"><a href=\"#\"> 카카오톡 문의하기 </a></div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 도매 대량구매 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"> 031-904-8072 </div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 1:1 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"><a href=\"");
      out.print(WebURL2 );
      out.write("/project/board/question_list_board.jsp\"> 1:1 문의하기 > </a></div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">궁금한 점이 있으신가요?</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">1:1 문의에 남겨주시면 </p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">친절히 답변 드리겠습니다.</p>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footUldiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul id=\"footUl\">\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"#\" class=\"footmenu\">회사소개</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"#\" class=\"footmenu\">이용안내</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"/edgeliving/project/policy/policy_info.jsp\" class=\"footmenu\">개인정보취급방침</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"/edgeliving/project/policy/policy_use.jsp\" class=\"footmenu\">이용약관</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footText\">\r\n");
      out.write("\t\t\t<ul id=\"footUl2\">\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 법인명(상호) : <strong>주식회사 반장조</strong></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 대표자(성명) : 전누리 </li>\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 개인정보보호책임자 : 김소현(김소현@naver.com)</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footText2\">\r\n");
      out.write("\t\t\t<ul id=\"footUl3\">\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 사업자등록번호 : <strong>111-22-333333</strong></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 통신판매번호 : 2019-디아망-1234 </li>\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 주소 : 서울특별시 종로구 율곡로10길 105 4층 중앙HTA</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
