/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-16 02:35:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.project.checkout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.JoinOrderMemProdVO;
import dao.JoinOrderMemProdDAO;
import dao.OrdersDAO;
import java.text.DecimalFormat;
import dao.JoinCartMemberProdDAO;
import vo.JoinCartMemberProdVO;
import dao.CartDAO;
import vo.ProductVO;
import dao.ProductDAO;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Set;
import vo.MemberVO;
import java.util.ArrayList;

public final class orderlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/project/checkout/../common/header.jsp", Long.valueOf(1579140940086L));
    _jspx_dependants.put("/project/checkout/../common/footer.jsp", Long.valueOf(1579140940075L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("dao.ProductDAO");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("vo.ProductVO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("dao.JoinOrderMemProdDAO");
    _jspx_imports_classes.add("dao.JoinCartMemberProdDAO");
    _jspx_imports_classes.add("dao.OrdersDAO");
    _jspx_imports_classes.add("vo.JoinCartMemberProdVO");
    _jspx_imports_classes.add("dao.CartDAO");
    _jspx_imports_classes.add("vo.MemberVO");
    _jspx_imports_classes.add("vo.JoinOrderMemProdVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\" integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<title>주문조회</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/main.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.cookie.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar jbOffset = $(\"#topMenu\").offset();\r\n");
      out.write("\t\tconsole.log(jbOffset);\r\n");
      out.write("\t\t$(window).scroll(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif ($(document).scrollTop() > jbOffset.top) {\r\n");
      out.write("\t\t\t\t$(\"#topMenu\").addClass(\"jbFixed\");\r\n");
      out.write("\t\t\t\t$(\"#contents\").addClass(\"bodyDown\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#topMenu\").removeClass(\"jbFixed\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar ck = document.getElementById(\"checkAll\");\r\n");
      out.write("\t\tck.onclick = function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar items  = document.getElementsByName('ck');\r\n");
      out.write("\t\t\t//console.dir(items);\r\n");
      out.write("\t\t\tfor(var i =0 ;i<items.length;i++){\r\n");
      out.write("\t\t\t\tvar box = items[i];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tbox.checked=ck.checked;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#viewcart_list_deleteBtn\").on(\"click\",function(){\r\n");
      out.write("\t\t\tdocument.frm.action=\"cartDeleteList.jsp\";\r\n");
      out.write("\t\t\tdocument.frm.method=\"get\";\r\n");
      out.write("\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t \t$(\"#cart_checkoutBtn\").on(\"click\",function(){\r\n");
      out.write("\t\t\tdocument.frm.action=\"../checkout/checkout.jsp\";\r\n");
      out.write("\t\t\tdocument.frm.method=\"post\";\r\n");
      out.write("\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t \r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#viewcart_contents{\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tmargin-top: 50px;\r\n");
      out.write("\tmargin-bottom: 150px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#viewcart_info{\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight : 73px;\r\n");
      out.write("\tborder : 1px solid #ced4da;\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#viewcart_info1{\r\n");
      out.write("\tmargin : 0px auto;\r\n");
      out.write("\twidth : 100px;\r\n");
      out.write("\theight: 53px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder-right : 1px solid #ced4da;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#viewcart_info2{\r\n");
      out.write("margin : 0px auto;\r\n");
      out.write("\twidth : 1000px;\r\n");
      out.write("\theight: 73px;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".viewcart_info3class{\r\n");
      out.write("\t\r\n");
      out.write("\twidth: 990px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tmargin-left : 20px;\r\n");
      out.write("\tpadding-top: 7px;\r\n");
      out.write("\tborder-bottom: 1px solid #ced4da;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("#checkout_conditions{\r\n");
      out.write("\tborder: 1px solid gray;\r\n");
      out.write("\tmargin-top: 120px;\r\n");
      out.write("\t\r\n");
      out.write("\tmargin-bottom: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#checkout_conditions_head{\r\n");
      out.write("\tbackground: #f9f9f9;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tborder-bottom: 1px solid grary;\r\n");
      out.write("\tpadding-top: 5px;\r\n");
      out.write("    padding-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("#checkout_conditions_body{\r\n");
      out.write("\tfont-size: small;\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("#checkout_conditions_body li{\r\n");
      out.write("\tdisplay: list-item;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#viewcart_deletebtndiv{\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("#viewcart_deletebtndiv1{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 600px; \r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\t\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("#viewcart_deletebtndiv2{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 590px; \r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#viewcart_deletebtndiv3{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\t\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write(".pagination{\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	Object viewcartobj = session.getAttribute("vo");
	if(viewcartobj != null){
	MemberVO mVO2 = (MemberVO)viewcartobj;
	OrdersDAO oDAO = new OrdersDAO();
	JoinOrderMemProdDAO jDAO = new JoinOrderMemProdDAO();
	int mno = mVO2.getMno();
	int totalCount = oDAO.getTotalCount(mno);
	int recordPerPage = 10;
	int totalPage = (totalCount % recordPerPage == 0)
			? totalCount / recordPerPage
			: totalCount / recordPerPage + 1;

	String cp = request.getParameter("cp");
	int currentPage = 0;
	if (cp != null) {
		currentPage = Integer.parseInt(cp);
	} else {
		currentPage = 1;
	}

	int startNo = (currentPage - 1) * recordPerPage + 1;
	int endNo = currentPage * recordPerPage;
	int startPage = 1;
	int endPage = totalPage;

	//시작페이지 끝페이지의 미세조정
	if (currentPage <= 5) {
		startPage = 1;
	} else if (currentPage >= 6) {
		startPage = currentPage - 4;
	}
	//끝페이지의 미세조정
	//현재페이지가 17이면 맨마지막페이지가18
	if (totalPage - currentPage <= 5) {
		endPage = totalPage;
	} else if (totalPage - currentPage > 5) {
		if (currentPage <= 5) {
			if (totalPage > 10) {
				endPage = 10;
			} else {
				endPage = totalPage;
			}
		} else {
			endPage = currentPage + 4;
		}

	}

      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

   
    	//String homeURL = "http://192.168.0.4:8080/edgeliving/project";
    	String homeURL = "/edgeliving/project";
    	//String homeURL = "http://192.168.0.4:8080/edgeliving/project";
    	String WebURL = "/edgeliving";
    
    
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t\t<div class=\"header1\" >\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL);
      out.write("/index.jsp\"><img src=\"");
      out.print(WebURL );
      out.write("/semiImages/logo.png\" alt=\"logo.png\"  id=\"mainlogo\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header1\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<strong>인기검색어</strong> <a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=자크라디\" class=\"search_a\">자크라디</a> &nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=임페리얼\" class=\"search_a\">임페리얼 포셀린</a> &nbsp; \r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=보니타하우스\"\tclass=\"search_a\">보니타하우스</a> &nbsp;\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp\" id=\"search_form\" name=\"search_frm\" onsubmit=\"return checkSearch()\">\r\n");
      out.write("\t\t\t \t\t<input type=\"text\" value=\"\" name=\"search\" size=\"40\" id=\"header_search_text\"/>\r\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"검색\" />\r\n");
      out.write("\t\t\t \t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checkSearch(){\r\n");
      out.write("\t\t\tif(search_frm.search.value == \"\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t    alert(\"값을 입력해 주세요.\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t    search_frm.search.focus();\r\n");
      out.write("\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t  }else{\r\n");
      out.write("\t\t\t\t  return true;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t  \r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t");


		Object obj = session.getAttribute("vo");
		
		MemberVO mVO = (MemberVO)obj;
		//
		if(obj == null){
			
		 
		
		
      out.write("\r\n");
      out.write("\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">로그인</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/member/register.jsp\" class=\"header_a2\">회원가입</a> <a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");

		}else{
			
			if(mVO.getAuthority() < 99){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/logout.jsp\" class=\"header_a2\">로그아웃</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/myPage/myPage.jsp\"  class=\"header_a2\">마이페이지</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/mainpage/viewcart.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/checkout/orderlist.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

				
			}else{
				
      out.write("\r\n");
      out.write("\t\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/logout.jsp\" class=\"header_a2\">로그아웃</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/myPage/myPage.jsp\"  class=\"header_a2\">마이페이지</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/mainpage/viewcart.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/checkout/orderlist.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/admin/main.jsp\" class=\"header_a2\">관리자페이지</a>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

			}
		}
		
      out.write("\r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t\t\t<ul id=\"topMenu\">\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=0\" class=\"menu\" id=\"allCategory\">전체상품</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=1\" class=\"menu\" id=\"newProd\">신상품</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=2\" class=\"menu\" id=\"best50\">베스트40</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/brand/brand.jsp\" class=\"menu\" id=\"brand\">브랜드</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/board/review.jsp\" class=\"menu\" id =\"review\">생생후기</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"contents\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");



			ArrayList<JoinOrderMemProdVO> list = jDAO.orderlistOne(startNo, endNo, mno);
		
	
      out.write("\r\n");
      out.write("\t<div id=\"viewcart_contents\">\r\n");
      out.write("\t\t<h3>주문조회</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"viewcart_info\">\r\n");
      out.write("\t\t\t<div id=\"viewcart_info1\">\r\n");
      out.write("\t\t\t\t<h6>혜택정보</h6>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"viewcart_info2\">\r\n");
      out.write("\t\t\t\t<div class=\"viewcart_info3class\">\r\n");
      out.write("\t\t\t\t");

					String strAutority = "일반회원";
					if(mVO2.getAuthority() == 1){
						strAutority = "일반회원";
					}else if(mVO2.getAuthority() == 99){
						strAutority = "관리자";
					}else{
						strAutority = "VIP";
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.print(mVO2.getMname() );
      out.write("님은 [");
      out.print(strAutority );
      out.write("] 회원입니다.\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"viewcart_info3class\">\r\n");
      out.write("\t\t\t\t\t사용가능 포인트 : ");
      out.print(mVO2.getPoint() );
      out.write("원   \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"viewcart_list\">\r\n");
      out.write("\t\t\t<h5>주문건 (");
      out.print(totalCount );
      out.write(")</h5>\r\n");
      out.write("\t\t\t<form  name=\"frm\">\r\n");
      out.write("\t\t\t<table class=\"table table-striped table-bordered\"\tstyle=\"width: 1200px; text-align: center\">\r\n");
      out.write("\t\t\t\t<tr style=\"font-size:14px; \">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>주문번호</th>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th>이미지</th>\r\n");
      out.write("\t\t\t\t\t<th>상품정보</th>\r\n");
      out.write("\t\t\t\t\t<th>수량</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th>상품구매금액<br />(배송비 포함)</th>\r\n");
      out.write("\t\t\t\t\t<th>주문처리상태</th>\r\n");
      out.write("\t\t\t\t\t<th>구매확정</th>\r\n");
      out.write("\t\t\t\t\t<th>리뷰쓰기</th>\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

				DecimalFormat df = new DecimalFormat("#,###");
					for(JoinOrderMemProdVO vo : list){
						int price = (int)(vo.getOrderprice() * (1 - (vo.getOrderdc() * 0.01)));
						int totalprice = vo.getOrderqty() * price;
						String strStatus = "";
						if(vo.getOrderstatus() == 1){
							strStatus = "배송준비 중";
						}else if(vo.getOrderstatus() == 2){
							strStatus = "배송중";
						}else if(vo.getOrderstatus() == 3){
							strStatus = "배송완료";
						}else if(vo.getOrderstatus() == 4){
							strStatus = "구매확정";
						}else if(vo.getOrderstatus() == 5){
							strStatus = "반품";
						}else if(vo.getOrderstatus() == 6){
							strStatus = "환불";
						}else if(vo.getOrderstatus() == 0){
							strStatus = "입급확인중";
						}
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr style=\"height: 80px; text-align: center ;\" >\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 180px\">");
      out.print(vo.getOrderno() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 80px; height: 80px;\"><img src=\"");
      out.print(vo.getThumbnailimg());
      out.write("\" alt=\"");
      out.print(vo.getThumbnailimg());
      out.write("\" width=\"50px\" height=\"50px\" /></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 680px; font-size: 12px; text-align: left; padding-left: 10px;\">");
      out.print(vo.getPname());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 100px;font-size: 12px;\">");
      out.print(df.format(vo.getOrderqty()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 170px;font-size: 12px;\">");
      out.print(df.format(totalprice+2500));
      out.write("원</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 100px;font-size: 12px;\">");
      out.print(strStatus );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td style=\"width : 140px;font-size: 12px;\">\r\n");
      out.write("\t\t\t\t\t<input\ttype=\"button\" value=\"구매확정\" id=\"order_finish\" /></td>\r\n");
      out.write("\t\t\t\t\t<td  style=\"width : 70px;;font-size: 12px;\">\r\n");
      out.write("\t\t\t\t\t<a\thref=\"../board/reviewWrite.jsp?orderno=");
      out.print(vo.getOrderno());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"작성\" id=\"write_review\"/></a></td>\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t\t");
	
					}
				
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"viewcart_deletebtndiv\">\r\n");
      out.write("\t\t\t<div id=\"viewcart_deletebtndiv1\"></div>\r\n");
      out.write("\t\t\t<div id=\"viewcart_deletebtndiv2\">\r\n");
      out.write("\t\t\t\t<nav aria-label=\"Page navigation example\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"page-link\" href=\"orderlist.jsp?cp=1\" aria-label=\"Previous\">\r\n");
      out.write("        \t\t\t\t\t<span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("     \t\t\t\t\t\t </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write(" <!-- 누를때마다 커런트페이지가 바뀌도록  --> \r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\"\thref=\"orderlist.jsp?cp=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t ");

 			
				}
			
      out.write("\r\n");
      out.write("\t\t\t\t\t  <li class=\"page-item\">\r\n");
      out.write("     \t\t\t\t\t <a class=\"page-link\" href=\"orderlist.jsp?cp=");
      out.print(endPage );
      out.write("\" aria-label=\"Next\">\r\n");
      out.write("       \t\t\t\t\t <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("      \t\t\t\t\t</a>\r\n");
      out.write("    \t\t \t\t </li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"viewcart_deletebtndiv3\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"checkout_conditions\">\r\n");
      out.write("\t\t\t<div id=\"checkout_conditions_head\">\r\n");
      out.write("\t\t\t\t<h5>이용안내</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"checkout_conditions_body\">\r\n");
      out.write("\t\t\t\t<div id=\"checkout_conditions_1\">\r\n");
      out.write("\t\t\t\t\t<h6>장바구니 이용안내</h6>\r\n");
      out.write("\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t<li>해외배송 상품과 국내배송 상품은 함께 결제하실 수 없으니 장바구니 별로 따로 결제해 주시기 바랍니다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li>해외배송 가능 상품의 경우 국내배송 장바구니에 담았다가 해외배송 장바구니로 이동하여 결제하실 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li>선택하신 상품의 수량을 변경하시려면 수량변경 후 [변경] 버튼을 누르시면 됩니다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li>[쇼핑계속하기] 버튼을 누르시면 쇼핑을 계속 하실 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li>장바구니와 관심상품을 이용하여 원하시는 상품만 주문하거나 관심상품으로 등록하실 수 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li>파일첨부 옵션은 동일상품을 장바구니에 추가할 경우 마지막에 업로드 한 파일로 교체됩니다.</li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"checkout_conditions_2\">\r\n");
      out.write("\t\t\t\t\t<h6>무이자할부 이용안내</h6>\r\n");
      out.write("\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t<li>상품별 무이자할부 혜택을 받으시려면 무이자할부 상품만 선택하여 [주문하기] 버튼을 눌러 주문/결제 하시면 됩니다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li>[전체 상품 주문] 버튼을 누르시면 장바구니의 구분없이 선택된 모든 상품에 대한 주문/결제가 이루어집니다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li>단, 전체 상품을 주문/결제하실 경우, 상품별 무이자할부 혜택을 받으실 수 없습니다.</li>\r\n");
      out.write("\t\t\t\t\t</ol>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("  \r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \t");
 String WebURL2 = "/edgeliving";
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 고객센터</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"> 031-904-8072 </div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t<p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 카카오톡 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"><a href=\"#\"> 카카오톡 문의하기 </a></div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 도매 대량구매 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"> 031-904-8072 </div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 1:1 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"><a href=\"");
      out.print(WebURL2 );
      out.write("/project/board/question_list_board.jsp\"> 1:1 문의하기 > </a></div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">궁금한 점이 있으신가요?</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">1:1 문의에 남겨주시면 </p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">친절히 답변 드리겠습니다.</p>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footUldiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul id=\"footUl\">\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"#\" class=\"footmenu\">회사소개</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"#\" class=\"footmenu\">이용안내</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"/edgeliving/project/policy/policy_info.jsp\" class=\"footmenu\">개인정보취급방침</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"/edgeliving/project/policy/policy_use.jsp\" class=\"footmenu\">이용약관</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footText\">\r\n");
      out.write("\t\t\t<ul id=\"footUl2\">\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 법인명(상호) : <strong>주식회사 반장조</strong></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 대표자(성명) : 전누리 </li>\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 개인정보보호책임자 : 김소현(김소현@naver.com)</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footText2\">\r\n");
      out.write("\t\t\t<ul id=\"footUl3\">\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 사업자등록번호 : <strong>111-22-333333</strong></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 통신판매번호 : 2019-디아망-1234 </li>\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 주소 : 서울특별시 종로구 율곡로10길 105 4층 중앙HTA</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');

	}else{
		response.sendRedirect("../index.jsp");	
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
