/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-16 02:35:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.project.mainpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import vo.ProductVO;
import java.util.ArrayList;
import dao.ProductDAO;
import vo.MemberVO;
import java.util.ArrayList;

public final class productdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/project/mainpage/../common/header.jsp", Long.valueOf(1579140940086L));
    _jspx_dependants.put("/project/mainpage/../common/footer.jsp", Long.valueOf(1579140940075L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("dao.ProductDAO");
    _jspx_imports_classes.add("vo.MemberVO");
    _jspx_imports_classes.add("vo.ProductVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>상품정보</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/main.css\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.cookie.js\"></script>\r\n");
      out.write("\r\n");

 
   String p = request.getParameter("pno");
   DecimalFormat df = new DecimalFormat("#,###");
   
   if(p!=null){
      int pno = Integer.parseInt(p);
      
      ProductDAO dao = new ProductDAO();
      ProductVO vo = dao.getOne(pno);
      


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("  \t#container{\r\n");
      out.write("\twidth: 1500px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.blank {\r\n");
      out.write("\twidth: 1500px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t#productdetail_thumbnailImg {\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t\theight:400px;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin-left: 100px;\r\n");
      out.write("\t\tmargin-right: 50px;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t#big_table {\r\n");
      out.write("\tborder-top: 2px solid gray;\r\n");
      out.write("\tborder-bottom: 2px solid gray;\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.boxarea1{\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\theight:100px;\r\n");
      out.write("\t\tborder: 1px solid gray;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin-left: 100px;\r\n");
      out.write("\t\tpadding-top: 30px;\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.boxarea2{\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tborder: 1px solid gray;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin-left: 100px;\r\n");
      out.write("\t\tpadding-top: 30px;\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.block{\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.boxarea2:hover, .boxarea1:hover{\r\n");
      out.write("\t\tbackground : pink;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#buy, #cart, #wish {\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#buy {\r\n");
      out.write("\tbackground: #222222;\r\n");
      out.write("\twidth : 200px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("#buy:hover, #cart:hover, #wish:hover {\r\n");
      out.write("   background: pink;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t#detail_img_table{\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tborder-bottom: 2px solid gray;\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#detail_img{\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#detail_img_division{\r\n");
      out.write("\twidth:1000px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#plus, #minus{\r\n");
      out.write("\t\twidth: 25px;\r\n");
      out.write("\t\theight: 18px;\r\n");
      out.write("\t\tfont-size: 10px;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.table_middle_row {\r\n");
      out.write("\tborder-bottom: 2px solid gray;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#totalprice{\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("\t$(function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#buy\").on(\"click\",function(){\r\n");
      out.write("\t\t\tdocument.frm.action=\"../checkout/checkout.jsp\";\r\n");
      out.write("\t\t\tdocument.frm.method=\"post\";\r\n");
      out.write("\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t   ");

	   Object proddetailObj = session.getAttribute("vo");
	   
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("\t   \r\n");
      out.write("\t   $(\"#cart\").on(\"click\", function(){\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t\t\r\n");
      out.write("         \tvar pnoval = $(\"#pno\").val();\r\n");
      out.write("         \tvar qtyval = $(\"#num\").val();\r\n");
      out.write("         \tvar totalpriceval = $(\"#totalprice\").val();\r\n");
      out.write("\t\t   \twindow.open(\"./cartDialog.jsp?pno=\"+pnoval+\"&qty=\"+qtyval+\"&totalprice=\"+totalpriceval,\"new\",\"width=550,height=500,top=200,left=200\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("     });\r\n");
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("      \r\n");
      out.write("      var jbOffset = $(\"#topMenu\").offset();\r\n");
      out.write("\t\tconsole.log(jbOffset);\r\n");
      out.write("\t\t$(window).scroll(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(document).scrollTop() > jbOffset.top){\r\n");
      out.write("\t\t\t\t$(\"#topMenu\").addClass(\"jbFixed\");\r\n");
      out.write("\t\t\t\t$(\"#contents\").addClass(\"bodyDown\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#topMenu\").removeClass(\"jbFixed\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

   
    	//String homeURL = "http://192.168.0.4:8080/edgeliving/project";
    	String homeURL = "/edgeliving/project";
    	//String homeURL = "http://192.168.0.4:8080/edgeliving/project";
    	String WebURL = "/edgeliving";
    
    
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t\t<div class=\"header1\" >\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL);
      out.write("/index.jsp\"><img src=\"");
      out.print(WebURL );
      out.write("/semiImages/logo.png\" alt=\"logo.png\"  id=\"mainlogo\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header1\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<strong>인기검색어</strong> <a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=자크라디\" class=\"search_a\">자크라디</a> &nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=임페리얼\" class=\"search_a\">임페리얼 포셀린</a> &nbsp; \r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=보니타하우스\"\tclass=\"search_a\">보니타하우스</a> &nbsp;\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp\" id=\"search_form\" name=\"search_frm\" onsubmit=\"return checkSearch()\">\r\n");
      out.write("\t\t\t \t\t<input type=\"text\" value=\"\" name=\"search\" size=\"40\" id=\"header_search_text\"/>\r\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"검색\" />\r\n");
      out.write("\t\t\t \t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checkSearch(){\r\n");
      out.write("\t\t\tif(search_frm.search.value == \"\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t    alert(\"값을 입력해 주세요.\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t    search_frm.search.focus();\r\n");
      out.write("\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t  }else{\r\n");
      out.write("\t\t\t\t  return true;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t  \r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t");


		Object obj = session.getAttribute("vo");
		
		MemberVO mVO = (MemberVO)obj;
		//
		if(obj == null){
			
		 
		
		
      out.write("\r\n");
      out.write("\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">로그인</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/member/register.jsp\" class=\"header_a2\">회원가입</a> <a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");

		}else{
			
			if(mVO.getAuthority() < 99){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/logout.jsp\" class=\"header_a2\">로그아웃</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/myPage/myPage.jsp\"  class=\"header_a2\">마이페이지</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/mainpage/viewcart.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/checkout/orderlist.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

				
			}else{
				
      out.write("\r\n");
      out.write("\t\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/logout.jsp\" class=\"header_a2\">로그아웃</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/myPage/myPage.jsp\"  class=\"header_a2\">마이페이지</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/mainpage/viewcart.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/checkout/orderlist.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/admin/main.jsp\" class=\"header_a2\">관리자페이지</a>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

			}
		}
		
      out.write("\r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t\t\t<ul id=\"topMenu\">\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=0\" class=\"menu\" id=\"allCategory\">전체상품</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=1\" class=\"menu\" id=\"newProd\">신상품</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=2\" class=\"menu\" id=\"best50\">베스트40</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/brand/brand.jsp\" class=\"menu\" id=\"brand\">브랜드</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/board/review.jsp\" class=\"menu\" id =\"review\">생생후기</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"contents\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"blank\"></div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   <form name=\"frm\">\r\n");
      out.write("      <input type=\"hidden\" name=\"pno\" id=\"pno\" value=\"");
      out.print(vo.getPno() );
      out.write("\"  />\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <div id=\"container\">\r\n");
      out.write("      <div id=\"pic\">\r\n");
      out.write("      <img src=\"");
      out.print(vo.getThumbNailImg() );
      out.write("\" alt=\"");
      out.print(vo.getPname() );
      out.write("\" id=\"productdetail_thumbnailImg\" />\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div id=\"info\">\r\n");
      out.write("         <table id=\"big_table\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td colspan=\"3\"><h2>");
      out.print(vo.getPname() );
      out.write("</h2><p class=\"table_middle_row\"></p></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>소비자가<br></td>\r\n");
      out.write("               <td><del>");
      out.print(df.format(vo.getPrice()) );
      out.write("원</del><br></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         \r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("               <td><h3>판매가</h3></td>\r\n");
      out.write("               <td><h3>");
      out.print(df.format(Math.round((vo.getPrice()*(1-vo.getDiscount()*0.01))/100) *100));
      out.write("원</h3></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>제조사</td>\r\n");
      out.write("               <td>");
      out.print(vo.getBrandName() );
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>대분류</td>\r\n");
      out.write("               <td>");
      out.print(vo.getLargeCategory() );
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>배송비</td>\r\n");
      out.write("               <td>2,500원 (30,000원 이상 구매 시 무료)</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("               \r\n");
      out.write("               ");

                  int length = vo.getPname().length();
                  if(length >= 19 ){
               
      out.write("\r\n");
      out.write("                  <td>");
      out.print( vo.getPname().substring(0,15) + "..." );
      out.write("<br></td>\r\n");
      out.write("               ");
            
                  }else{
               
      out.write("\r\n");
      out.write("                  <td>");
      out.print(vo.getPname());
      out.write("<br></td>\r\n");
      out.write("               ");
      
                  }
               
      out.write("\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               <td>\r\n");
      out.write("\r\n");
      out.write("               <table>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                  <td rowspan=\"3\">\r\n");
      out.write("                   <input type=\"text\" name=\"qty\" id=\"num\" size=\"1\" value=1 /><br> \r\n");
      out.write("                  <!-- <input type=\"text\" name=\"qty\" id=\"qty\" size=\"1\" value=1 /><br> -->\r\n");
      out.write("                  </td>   \r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                  <td colspan=\"3\" >\r\n");
      out.write("                  <input type=\"button\" value=\"△\" id=\"plus\" onclick=\"add()\" /><br>\r\n");
      out.write("                  <input type=\"button\" value=\"▽\" id=\"minus\" onclick=\"minus2()\" />  \r\n");
      out.write("                   <br>\r\n");
      out.write("                  </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               </table>\r\n");
      out.write("               \r\n");
      out.write("               </td>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("               <script>\r\n");
      out.write("               \r\n");
      out.write("                  function  add(num){\r\n");
      out.write("                  var num = document.getElementById(\"num\");\r\n");
      out.write("                  num.value = num.value*1+1;\r\n");
      out.write("                  \r\n");
      out.write("                  var totalprice = document.getElementById(\"totalprice\");\r\n");
      out.write("                  totalprice.value = (totalprice.value/(num.value*1-1)*(num.value));\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("               }\r\n");
      out.write("                  \r\n");
      out.write("                  function btn_like2(){\r\n");
      out.write("                \t\r\n");
      out.write("              \t\t\talert(\"");
      out.print(vo.getPname());
      out.write("을 \\r\\n추천하셨습니다.\");\r\n");
      out.write("              \t\t\t");

              			int pnopno = vo.getPno();
              			dao.raiseLike(pnopno); 
      out.write("\r\n");
      out.write("              \t\t\t\r\n");
      out.write("              \t\t\t\r\n");
      out.write("              \t\t\t\r\n");
      out.write("              \t\t                \t  \r\n");
      out.write("                  }\r\n");
      out.write("                  \r\n");
      out.write("               function minus2(num){\r\n");
      out.write("                           \r\n");
      out.write("                     var num = document.getElementById(\"num\");\r\n");
      out.write("                     num.value = num.value*1-1;   \r\n");
      out.write("                        \r\n");
      out.write("                     \r\n");
      out.write("                     if(num.value <= 0){      \r\n");
      out.write("                        alert(\"1개 보다 적게 구입할 수는 없습니다.\");\r\n");
      out.write("                        num.value=1;\r\n");
      out.write("                        //고치기\r\n");
      out.write("                        totalprice2.value = totalprice2.value*(num*1+1); \r\n");
      out.write("                     }else{\r\n");
      out.write("                     var totalprice2 = document.getElementById(\"totalprice\");\r\n");
      out.write("                     console.log(\"현재 토탈 가격 표시\" + totalprice2.value);\r\n");
      out.write("                     console.log(\"수식 적용 가격\" + totalprice2.value/(num.value*1+1));\r\n");
      out.write("                     console.log(\"수향: \" + num.value);\r\n");
      out.write("                     totalprice2.value = (totalprice2.value/(num.value*1+1)*(num.value));\r\n");
      out.write("                        \r\n");
      out.write("                     }\r\n");
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                     \r\n");
      out.write("                  }\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("               </script>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td><h3>Total Price</h3></td>\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("               <td><h3><input type=\"text\" name=\"totalprice\" id=\"totalprice\" size=\"10\" value=\"");
      out.print( Math.round((vo.getPrice()*(1-vo.getDiscount()*0.01))/100) *100 );
      out.write("\" readonly />원\r\n");
      out.write("               \r\n");
      out.write("               </h3></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               <input type=\"button\" value=\"BUY NOW\"  id=\"buy\"/></td>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               <td><input type=\"button\" value=\"ADD TO CART\" id=\"cart\"/>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               <a href=\"viewcart.jsp\"><input type=\"button\" value=\"WISHLIST\" id=\"wish\" /></a>\r\n");
      out.write("               \r\n");
      out.write("               </td>\r\n");
      out.write("               \r\n");
      out.write("            </tr>\r\n");
      out.write("      \r\n");
      out.write("         </table>\r\n");
      out.write("         \t<!--  추가 -->\r\n");
      out.write("         \t<div class=\"boxarea1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"\"><input type=\"button\" value=\"Like!☆\"  id=\"btn_like\" onclick=\"btn_like2();\" /><br>좋아요</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"boxarea2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"\">상품문의 <a href=\"../board/question_write_board.jsp?pno=");
      out.print(vo.getPno());
      out.write("\"><br>쓰기</a></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("      </form>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <table id=\"detail_img_table\">\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td><h2>상품 상세 정보</h2></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("      \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   <div id=\"detail_img_division\">\r\n");
      out.write("       ");
      out.print(vo.getDetailDesc() );
      out.write("\r\n");
      out.write("   </div>    \r\n");
      out.write("   \r\n");
      out.write("   <div id=\"dialog\" title=\"공지사항\" style=\"display: none; text-align: center;\">\r\n");
      out.write("    <h3> 장바구니에 추가 하시겠습니까? </h3>\r\n");
      out.write("    <img src=\"");
      out.print(vo.getThumbNailImg() );
      out.write("\" alt=\"\" style=\"width: 200px; height: 200px;\" />\r\n");
      out.write("    ");
      out.print( vo.getPname() );
      out.write("<br>\r\n");
      out.write("    \t    \r\n");
      out.write("\t</div>    \r\n");
      out.write("   ");

      } 
   
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div class=\"blank\"></div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("    \t");
 String WebURL2 = "/edgeliving";
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 고객센터</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"> 031-904-8072 </div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t<p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 카카오톡 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"><a href=\"#\"> 카카오톡 문의하기 </a></div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 도매 대량구매 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"> 031-904-8072 </div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 1:1 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"><a href=\"");
      out.print(WebURL2 );
      out.write("/project/board/question_list_board.jsp\"> 1:1 문의하기 > </a></div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">궁금한 점이 있으신가요?</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">1:1 문의에 남겨주시면 </p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">친절히 답변 드리겠습니다.</p>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footUldiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul id=\"footUl\">\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"#\" class=\"footmenu\">회사소개</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"#\" class=\"footmenu\">이용안내</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"/edgeliving/project/policy/policy_info.jsp\" class=\"footmenu\">개인정보취급방침</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"/edgeliving/project/policy/policy_use.jsp\" class=\"footmenu\">이용약관</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footText\">\r\n");
      out.write("\t\t\t<ul id=\"footUl2\">\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 법인명(상호) : <strong>주식회사 반장조</strong></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 대표자(성명) : 전누리 </li>\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 개인정보보호책임자 : 김소현(김소현@naver.com)</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footText2\">\r\n");
      out.write("\t\t\t<ul id=\"footUl3\">\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 사업자등록번호 : <strong>111-22-333333</strong></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 통신판매번호 : 2019-디아망-1234 </li>\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 주소 : 서울특별시 종로구 율곡로10길 105 4층 중앙HTA</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
