/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-16 02:51:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.project.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import vo.ProductVO;
import dao.ProductDAO;
import vo.MemberVO;
import java.util.ArrayList;

public final class prodlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/project/product/./newProdlist.jsp", Long.valueOf(1579140940957L));
    _jspx_dependants.put("/project/product/./newProdlist2.jsp", Long.valueOf(1579140940981L));
    _jspx_dependants.put("/project/product/../common/footer.jsp", Long.valueOf(1579140940075L));
    _jspx_dependants.put("/project/product/../common/header.jsp", Long.valueOf(1579140940086L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("dao.ProductDAO");
    _jspx_imports_classes.add("vo.MemberVO");
    _jspx_imports_classes.add("vo.ProductVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>상품 리스트</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/main.css\" type=\"text/css\" />\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\">   </script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar jbOffset = $(\"#topMenu\").offset();\r\n");
      out.write("\tconsole.log(jbOffset);\r\n");
      out.write("\t$(window).scroll(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(document).scrollTop() > jbOffset.top){\r\n");
      out.write("\t\t\t$(\"#topMenu\").addClass(\"jbFixed\");\r\n");
      out.write("\t\t\t$(\"#contents\").addClass(\"bodyDown\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#topMenu\").removeClass(\"jbFixed\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\t.bodyDown{\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write(".prodlist_listDiv {\r\n");
      out.write("\twidth: 320px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\theight: 380px;\r\n");
      out.write("\tpadding-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".prodlist_Img {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("}\r\n");
      out.write("#prodlist_pageDiv{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tpadding-bottom: 120px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#prodlist_pageDiv:hover {\r\n");
      out.write("\tcolor: pink;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#prodlist_mainDiv{\r\n");
      out.write("\twidth: 1920px;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\t\r\n");
      out.write("\tpadding-top : 50px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#prodlist_imgDiv{\r\n");
      out.write("\tmargin-left: 300px;\r\n");
      out.write("\tmargin-right: 300px;\r\n");
      out.write("\tpadding-bottom: 100px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#prodlist_totalcount{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("}\r\n");
      out.write("#prodlist_orderlist{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 720px;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("#prodlist_countlistDiv{\r\n");
      out.write("\twidth: 1270px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\t\r\n");
      out.write("\tborder-top : 1px solid gray;\r\n");
      out.write("\tpadding-top : 20px;\r\n");
      out.write("\tpadding-bottom: 20px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#prodlist_mainLogoDiv{\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\t\r\n");
      out.write("\tmargin-top: 50px;\r\n");
      out.write("\tpadding-top : 20px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#prodlist_largecategoryDiv{\r\n");
      out.write("\tpadding-bottom: 30px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".prodlist_largecategory_btn{\r\n");
      out.write(" \tcolor: gray; \r\n");
      out.write(" \tfont-size: 12px; \r\n");
      out.write(" \tbackground: white; \r\n");
      out.write(" \tpadding: 5px 5px 5px 5px; \r\n");
      out.write(" \twidth: 100px; \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		String queryStr = request.getQueryString();
		String cate_no = request.getParameter("cate_no");
		String reqOrdername = request.getParameter("ordername");
		String reqLargecategory = request.getParameter("la_ca");
		if(reqOrdername == null){
			reqOrdername = "pno";
		}
		if(reqLargecategory == null){
			reqLargecategory = "";
		}
//		String ordername = "pno";
		String ordername = reqOrdername;
		String brandname = "";
		String largecategory = reqLargecategory;
		String searchBrand = "";
		String searchLargeCategory="";
		DecimalFormat df = new DecimalFormat("#,###");
		ProductDAO pDAO = new ProductDAO();
		int totalCount = 40;
		if (cate_no.equals("1") || cate_no == null) {
			 totalCount = 40;	
		}else if(cate_no.equals("2")){
			totalCount = 40;	
		}else if(cate_no.equals("3")){
			brandname = "자크라디";
			largecategory = reqLargecategory;
			searchBrand = brandname;
			searchLargeCategory = largecategory;
			totalCount = pDAO.getTotalCount(brandname, largecategory);	
		}else if(cate_no.equals("4")){
			brandname = "밀레나";
			largecategory = reqLargecategory;
			searchBrand = brandname;
			searchLargeCategory = largecategory;
			totalCount = pDAO.getTotalCount(brandname, largecategory);	
		}else if(cate_no.equals("5")){
			brandname = "임페리얼포슬린";
			largecategory = reqLargecategory;
			searchBrand = brandname;
			searchLargeCategory = largecategory;
			totalCount = pDAO.getTotalCount(brandname, largecategory);	
		}else if(cate_no.equals("6")){
			brandname = "로얄크라운더비";
			largecategory = reqLargecategory;
			searchBrand = brandname;
			searchLargeCategory = largecategory;
			totalCount = pDAO.getTotalCount(brandname, largecategory);	
		}else if(cate_no.equals("7")){
			brandname = "체스키포슬란";
			largecategory = reqLargecategory;
			searchBrand = brandname;
			searchLargeCategory = largecategory;
			totalCount = pDAO.getTotalCount(brandname, largecategory);	
		}else if(cate_no.equals("8")){
			brandname = "크리스탈렉스";
			largecategory = reqLargecategory;
			searchBrand = brandname;
			searchLargeCategory = largecategory;
			totalCount = pDAO.getTotalCount(brandname, largecategory);	
		}else if(cate_no.equals("9")){
			brandname = "마스터클래스";
			largecategory = reqLargecategory;
			searchBrand = brandname;
			searchLargeCategory = largecategory;
			totalCount = pDAO.getTotalCount(brandname, largecategory);	
		}else if(cate_no.equals("10")){
			brandname = "알타미라";
			largecategory = reqLargecategory;
			searchBrand = brandname;
			searchLargeCategory = largecategory;
			totalCount = pDAO.getTotalCount(brandname, largecategory);	
		}else if(cate_no.equals("11")){
			brandname = "비쥬";
			largecategory = reqLargecategory;
			searchBrand = brandname;
			searchLargeCategory = largecategory;
			totalCount = pDAO.getTotalCount(brandname, largecategory);	
		}
		
		else {
			brandname = "";
			largecategory = reqLargecategory;
			searchBrand = brandname;
			searchLargeCategory = largecategory;
			totalCount = pDAO.getTotalCount();
		}
		int recordPerPage = 40;
		int totalPage = (totalCount % recordPerPage == 0) ? totalCount / recordPerPage
				: totalCount / recordPerPage + 1;

		String cp = request.getParameter("cp");
		int currentPage = 0;
		if (cp != null) {
			currentPage = Integer.parseInt(cp);
		} else {
			currentPage = 1;
		}

		int startNo = (currentPage - 1) * recordPerPage + 1;
		int endNo = currentPage * recordPerPage;
		int startPage = 1;
		int endPage = totalPage;

		//시작페이지 끝페이지의 미세조정
		if (currentPage <= 5) {
			startPage = 1;
		} else if (currentPage >= 6) {
			startPage = currentPage - 4;
		}
		//끝페이지의 미세조정
		//현재페이지가 17이면 맨마지막페이지가18
		if (totalPage - currentPage <= 5) {
			endPage = totalPage;
		} else if (totalPage - currentPage > 5) {
			if (currentPage <= 5) {
				if (totalPage > 10) {
					endPage = 10;
				} else {
					endPage = totalPage;
				}
			} else {
				endPage = currentPage + 4;
			}

		}
		String h2Tag = "";
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

   
    	//String homeURL = "http://192.168.0.4:8080/edgeliving/project";
    	String homeURL = "/edgeliving/project";
    	//String homeURL = "http://192.168.0.4:8080/edgeliving/project";
    	String WebURL = "/edgeliving";
    
    
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t\t<div class=\"header1\" >\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL);
      out.write("/index.jsp\"><img src=\"");
      out.print(WebURL );
      out.write("/semiImages/logo.png\" alt=\"logo.png\"  id=\"mainlogo\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header1\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<strong>인기검색어</strong> <a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=자크라디\" class=\"search_a\">자크라디</a> &nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=임페리얼\" class=\"search_a\">임페리얼 포셀린</a> &nbsp; \r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=보니타하우스\"\tclass=\"search_a\">보니타하우스</a> &nbsp;\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp\" id=\"search_form\" name=\"search_frm\" onsubmit=\"return checkSearch()\">\r\n");
      out.write("\t\t\t \t\t<input type=\"text\" value=\"\" name=\"search\" size=\"40\" id=\"header_search_text\"/>\r\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"검색\" />\r\n");
      out.write("\t\t\t \t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checkSearch(){\r\n");
      out.write("\t\t\tif(search_frm.search.value == \"\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t    alert(\"값을 입력해 주세요.\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t    search_frm.search.focus();\r\n");
      out.write("\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t  }else{\r\n");
      out.write("\t\t\t\t  return true;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t  \r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t");


		Object obj = session.getAttribute("vo");
		
		MemberVO mVO = (MemberVO)obj;
		//
		if(obj == null){
			
		 
		
		
      out.write("\r\n");
      out.write("\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">로그인</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/member/register.jsp\" class=\"header_a2\">회원가입</a> <a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");

		}else{
			
			if(mVO.getAuthority() < 99){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/logout.jsp\" class=\"header_a2\">로그아웃</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/myPage/myPage.jsp\"  class=\"header_a2\">마이페이지</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/mainpage/viewcart.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/checkout/orderlist.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

				
			}else{
				
      out.write("\r\n");
      out.write("\t\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/logout.jsp\" class=\"header_a2\">로그아웃</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/myPage/myPage.jsp\"  class=\"header_a2\">마이페이지</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/mainpage/viewcart.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/checkout/orderlist.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/admin/main.jsp\" class=\"header_a2\">관리자페이지</a>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

			}
		}
		
      out.write("\r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t\t\t<ul id=\"topMenu\">\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=0\" class=\"menu\" id=\"allCategory\">전체상품</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=1\" class=\"menu\" id=\"newProd\">신상품</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=2\" class=\"menu\" id=\"best50\">베스트40</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/brand/brand.jsp\" class=\"menu\" id=\"brand\">브랜드</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/board/review.jsp\" class=\"menu\" id =\"review\">생생후기</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"contents\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"contents\">\r\n");
      out.write("\r\n");
      out.write("\t\t");

			if (cate_no.equals("1") || cate_no == null) {
				
				
				h2Tag = "신상품";
				String orderbycategory = "pdate";
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, orderbycategory,ordername);
		
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t<h2 style=\"text-align: center;  padding-top: 50px\">");
      out.print(h2Tag);
      out.write("</h2>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 13px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 19) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
	
			}else if(cate_no.equals("2")){
				
				h2Tag = "베스트 40";
				String orderbycategory = "recommend";
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, orderbycategory,ordername);
		
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t<h2 style=\"text-align: center;  padding-top: 50px\">");
      out.print(h2Tag);
      out.write("</h2>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 13px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 19) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
	
			}else if(cate_no.equals("3")){
	
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, searchBrand, searchLargeCategory,ordername);
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_mainLogoDiv\">\r\n");
      out.write("\t\t\t<img src=\"../../semiImages/zark.PNG\" alt=\"../../semiImages/zark.png\"  style=\"text-align: center\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_largecategoryDiv\">\r\n");
      out.write("\t\t\t");

				ArrayList<String> list2 = pDAO.getLaragecategory(brandname);
				for (int i = 0 ; i < list2.size() ; i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"");
      out.print(list2.get(i) );
      out.write("\"  class=\"prodlist_largecategory_btn\" id=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("\" onclick=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("();\"/>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction prodlist_largecategory_btn");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\tvar prodlist_btn = $(\"#prodlist_largecategory_btn");
      out.print(i);
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"./prodlist.jsp?la_ca=\"+prodlist_btn.val()+\"&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t");
		
				}
			
      out.write("\r\n");
      out.write("\t\t\t<!--  대분류 넣기. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 14px; font-weight: bold ; border-bottom: 1px solid gray ; margin-left: 35px; margin-right: 35px; padding-bottom: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 21) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
		
			}else if(cate_no.equals("4")){
	
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, searchBrand, searchLargeCategory,ordername);
		
      out.write("\r\n");
      out.write("\t\t\t<div id=\"prodlist_mainLogoDiv\">\r\n");
      out.write("\t\t\t<img src=\"../../semiImages/milena.PNG\" alt=\"../../semiImages/zark.png\"  style=\"text-align: center\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_largecategoryDiv\">\r\n");
      out.write("\t\t\t");

				ArrayList<String> list2 = pDAO.getLaragecategory(brandname);
				for (int i = 0 ; i < list2.size() ; i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"");
      out.print(list2.get(i) );
      out.write("\"  class=\"prodlist_largecategory_btn\" id=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("\" onclick=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("();\"/>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction prodlist_largecategory_btn");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\tvar prodlist_btn = $(\"#prodlist_largecategory_btn");
      out.print(i);
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"./prodlist.jsp?la_ca=\"+prodlist_btn.val()+\"&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t");
		
				}
			
      out.write("\r\n");
      out.write("\t\t\t<!--  대분류 넣기. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 14px; font-weight: bold ; border-bottom: 1px solid gray ; margin-left: 35px; margin-right: 35px; padding-bottom: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 21) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\t\t");

			}else if(cate_no.equals("5")){
		
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, searchBrand, searchLargeCategory,ordername);
		
      out.write("\r\n");
      out.write("\t\t\t<div id=\"prodlist_mainLogoDiv\">\r\n");
      out.write("\t\t\t<img src=\"../../semiImages/impo.PNG\" alt=\"../../semiImages/zark.png\"  style=\"text-align: center\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_largecategoryDiv\">\r\n");
      out.write("\t\t\t");

				ArrayList<String> list2 = pDAO.getLaragecategory(brandname);
				for (int i = 0 ; i < list2.size() ; i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"");
      out.print(list2.get(i) );
      out.write("\"  class=\"prodlist_largecategory_btn\" id=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("\" onclick=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("();\"/>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction prodlist_largecategory_btn");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\tvar prodlist_btn = $(\"#prodlist_largecategory_btn");
      out.print(i);
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"./prodlist.jsp?la_ca=\"+prodlist_btn.val()+\"&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t");
		
				}
			
      out.write("\r\n");
      out.write("\t\t\t<!--  대분류 넣기. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 14px; font-weight: bold ; border-bottom: 1px solid gray ; margin-left: 35px; margin-right: 35px; padding-bottom: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 21) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\t\t");

			}else if(cate_no.equals("6")){
	
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, searchBrand, searchLargeCategory,ordername);
		
      out.write("\r\n");
      out.write("\t\t\t<div id=\"prodlist_mainLogoDiv\">\r\n");
      out.write("\t\t\t<img src=\"../../semiImages/rcd.PNG\" alt=\"../../semiImages/zark.png\"  style=\"text-align: center\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_largecategoryDiv\">\r\n");
      out.write("\t\t\t");

				ArrayList<String> list2 = pDAO.getLaragecategory(brandname);
				for (int i = 0 ; i < list2.size() ; i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"");
      out.print(list2.get(i) );
      out.write("\"  class=\"prodlist_largecategory_btn\" id=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("\" onclick=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("();\"/>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction prodlist_largecategory_btn");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\tvar prodlist_btn = $(\"#prodlist_largecategory_btn");
      out.print(i);
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"./prodlist.jsp?la_ca=\"+prodlist_btn.val()+\"&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t");
		
				}
			
      out.write("\r\n");
      out.write("\t\t\t<!--  대분류 넣기. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 14px; font-weight: bold ; border-bottom: 1px solid gray ; margin-left: 35px; margin-right: 35px; padding-bottom: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 21) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\t\t");

			}else if(cate_no.equals("7")){
	
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, searchBrand, searchLargeCategory,ordername);
		
      out.write("\r\n");
      out.write("\t\t\t<div id=\"prodlist_mainLogoDiv\">\r\n");
      out.write("\t\t\t<img src=\"../../semiImages/cesky.PNG\" alt=\"../../semiImages/zark.png\"  style=\"text-align: center\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_largecategoryDiv\">\r\n");
      out.write("\t\t\t");

				ArrayList<String> list2 = pDAO.getLaragecategory(brandname);
				for (int i = 0 ; i < list2.size() ; i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"");
      out.print(list2.get(i) );
      out.write("\"  class=\"prodlist_largecategory_btn\" id=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("\" onclick=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("();\"/>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction prodlist_largecategory_btn");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\tvar prodlist_btn = $(\"#prodlist_largecategory_btn");
      out.print(i);
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"./prodlist.jsp?la_ca=\"+prodlist_btn.val()+\"&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t");
		
				}
			
      out.write("\r\n");
      out.write("\t\t\t<!--  대분류 넣기. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 14px; font-weight: bold ; border-bottom: 1px solid gray ; margin-left: 35px; margin-right: 35px; padding-bottom: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 21) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\t\t");

			}else if(cate_no.equals("8")){
			
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, searchBrand, searchLargeCategory,ordername);
		
      out.write("\r\n");
      out.write("\t\t\t<div id=\"prodlist_mainLogoDiv\">\r\n");
      out.write("\t\t\t<img src=\"../../semiImages/crystal.PNG\" alt=\"../../semiImages/zark.png\"  style=\"text-align: center\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_largecategoryDiv\">\r\n");
      out.write("\t\t\t");

				ArrayList<String> list2 = pDAO.getLaragecategory(brandname);
				for (int i = 0 ; i < list2.size() ; i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"");
      out.print(list2.get(i) );
      out.write("\"  class=\"prodlist_largecategory_btn\" id=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("\" onclick=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("();\"/>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction prodlist_largecategory_btn");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\tvar prodlist_btn = $(\"#prodlist_largecategory_btn");
      out.print(i);
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"./prodlist.jsp?la_ca=\"+prodlist_btn.val()+\"&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t");
		
				}
			
      out.write("\r\n");
      out.write("\t\t\t<!--  대분류 넣기. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 14px; font-weight: bold ; border-bottom: 1px solid gray ; margin-left: 35px; margin-right: 35px; padding-bottom: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 21) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\t\t");

			}else if(cate_no.equals("9")){
				h2Tag = "마스터클래스";
		
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, searchBrand, searchLargeCategory,ordername);
		
      out.write("\r\n");
      out.write("\t\t\t<h2 style=\"text-align: center;  padding-top: 50px\">");
      out.print(h2Tag);
      out.write("</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_largecategoryDiv\">\r\n");
      out.write("\t\t\t");

				ArrayList<String> list2 = pDAO.getLaragecategory(brandname);
				for (int i = 0 ; i < list2.size() ; i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"");
      out.print(list2.get(i) );
      out.write("\"  class=\"prodlist_largecategory_btn\" id=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("\" onclick=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("();\"/>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction prodlist_largecategory_btn");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\tvar prodlist_btn = $(\"#prodlist_largecategory_btn");
      out.print(i);
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"./prodlist.jsp?la_ca=\"+prodlist_btn.val()+\"&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t");
		
				}
			
      out.write("\r\n");
      out.write("\t\t\t<!--  대분류 넣기. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 14px; font-weight: bold ; border-bottom: 1px solid gray ; margin-left: 35px; margin-right: 35px; padding-bottom: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 21) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\t\t");

			}else if(cate_no.equals("10")){
		
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, searchBrand, searchLargeCategory,ordername);
		
      out.write("\r\n");
      out.write("\t\t\t<div id=\"prodlist_mainLogoDiv\">\r\n");
      out.write("\t\t\t<img src=\"../../semiImages/altamira.PNG\" alt=\"../../semiImages/zark.png\"  style=\"text-align: center\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_largecategoryDiv\">\r\n");
      out.write("\t\t\t");

				ArrayList<String> list2 = pDAO.getLaragecategory(brandname);
				for (int i = 0 ; i < list2.size() ; i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"");
      out.print(list2.get(i) );
      out.write("\"  class=\"prodlist_largecategory_btn\" id=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("\" onclick=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("();\"/>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction prodlist_largecategory_btn");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\tvar prodlist_btn = $(\"#prodlist_largecategory_btn");
      out.print(i);
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"./prodlist.jsp?la_ca=\"+prodlist_btn.val()+\"&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t");
		
				}
			
      out.write("\r\n");
      out.write("\t\t\t<!--  대분류 넣기. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 14px; font-weight: bold ; border-bottom: 1px solid gray ; margin-left: 35px; margin-right: 35px; padding-bottom: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 21) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\t\t");

			}else if(cate_no.equals("11")){
				h2Tag = "비쥬";
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, searchBrand, searchLargeCategory,ordername);
		
      out.write("\r\n");
      out.write("\t\t\t<h2 style=\"text-align: center;  padding-top: 50px\">");
      out.print(h2Tag);
      out.write("</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_largecategoryDiv\">\r\n");
      out.write("\t\t\t");

				ArrayList<String> list2 = pDAO.getLaragecategory(brandname);
				for (int i = 0 ; i < list2.size() ; i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"");
      out.print(list2.get(i) );
      out.write("\"  class=\"prodlist_largecategory_btn\" id=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("\" onclick=\"prodlist_largecategory_btn");
      out.print(i);
      out.write("();\"/>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction prodlist_largecategory_btn");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\tvar prodlist_btn = $(\"#prodlist_largecategory_btn");
      out.print(i);
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"./prodlist.jsp?la_ca=\"+prodlist_btn.val()+\"&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t");
		
				}
			
      out.write("\r\n");
      out.write("\t\t\t<!--  대분류 넣기. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 14px; font-weight: bold ; border-bottom: 1px solid gray ; margin-left: 35px; margin-right: 35px; padding-bottom: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 21) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\t\t");

			}else if(cate_no.equals("0")){
				h2Tag = "전체 상품";
				String orderbycategory = "pno";
				ArrayList<ProductVO> list = pDAO.top40(startNo, endNo, orderbycategory,ordername);
		
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t<h2 style=\"text-align: center;  padding-top: 50px\">");
      out.print(h2Tag);
      out.write("</h2>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"prodlist_mainDiv\">\r\n");
      out.write("\t\t\t<div id=\"prodlist_imgDiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"prodlist_countlistDiv\">\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_totalcount\">\r\n");
      out.write("\t\t\t\t<p style=\"color: gray; font-size: 15px;\">총 ");
      out.print(totalCount );
      out.write("개의 상품이 등록되어 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"prodlist_orderlist\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"신상품\" id=\"prodlist_orderNew\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"상품명\" id=\"prodlist_orderPname\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew2();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"낮은가격\" id=\"prodlist_orderPriceup\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px; \" onclick=\"orderNew3();\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"높은가격\" id=\"prodlist_orderPricedown\" style=\"color: gray; font-size: 12px; background: white; padding: 5px 5px 5px 5px;\" onclick=\"orderNew4();\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");

					for (ProductVO vo2 : list) {
							int price2 = (int) (vo2.getPrice() * (1 - (vo2.getDiscount() * 0.01)));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"prodlist_listDiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write("\">\t<img src=\"");
      out.print(vo2.getThumbNailImg());
      out.write("\" alt=\"");
      out.print(vo2.getPname());
      out.write("\"\tclass=\"prodlist_Img\" /> </a>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 13px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								int length = vo2.getPname().length();
										if (length >= 19) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname().substring(0, 15) + "...");
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../mainpage/productdetail.jsp?pno=");
      out.print(vo2.getPno());
      out.write('"');
      out.write('>');
      out.write('	');
      out.print(vo2.getPname());
      out.write(" </a>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"mainPrice\">");
      out.print(df.format(vo2.getPrice()));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<strong class=\"strongPrice\"> ");
      out.print(df.format(Math.round(price2 * 0.01) * 100));
      out.write("원\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"prodlist_pageDiv\">\r\n");
      out.write("\t\t\t\t");

					for (int i = startPage; i <= endPage; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 누를때마다 커런트페이지가 바뀌도록  -->\r\n");
      out.write("\t\t\t\t<a href=\"prodlist.jsp?cp=");
      out.print(i);
      out.write('&');
      out.print(queryStr);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t");
		
			}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\t\tfunction orderNew(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tlocation.href=\"./prodlist.jsp?ordername=pdate desc &");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfunction orderNew2(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tlocation.href=\"./prodlist.jsp?ordername=pname&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfunction orderNew3(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tlocation.href=\"./prodlist.jsp?ordername=price&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfunction orderNew4(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tlocation.href=\"./prodlist.jsp?ordername=price desc&");
      out.print(queryStr);
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \t");
 String WebURL2 = "/edgeliving";
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 고객센터</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"> 031-904-8072 </div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t<p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 카카오톡 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"><a href=\"#\"> 카카오톡 문의하기 </a></div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 도매 대량구매 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"> 031-904-8072 </div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>평일</strong>오전 10시 ~ 오후 5시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>점심</strong>오전 12시 ~ 오후 1시</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\"><strong>휴무</strong>토/일/공휴일은 휴무</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div class=\"footdiv\">\r\n");
      out.write("\t\t\t<div class=\"footText\"> 1:1 문의</div>\r\n");
      out.write("\t\t\t<div class=\"footPhone\"><a href=\"");
      out.print(WebURL2 );
      out.write("/project/board/question_list_board.jsp\"> 1:1 문의하기 > </a></div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"footTimeImgDiv\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(WebURL2 );
      out.write("/semiImages/logo.jpg\" alt=\"footTimelogo.jpg\"  id=\"footTimelogo\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footPdiv\">\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">궁금한 점이 있으신가요?</p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">1:1 문의에 남겨주시면 </p>\r\n");
      out.write("\t\t\t\t <p class=\"footPtag\">친절히 답변 드리겠습니다.</p>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footUldiv\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul id=\"footUl\">\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"#\" class=\"footmenu\">회사소개</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"#\" class=\"footmenu\">이용안내</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"/edgeliving/project/policy/policy_info.jsp\" class=\"footmenu\">개인정보취급방침</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli\"><a href=\"/edgeliving/project/policy/policy_use.jsp\" class=\"footmenu\">이용약관</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footText\">\r\n");
      out.write("\t\t\t<ul id=\"footUl2\">\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 법인명(상호) : <strong>주식회사 반장조</strong></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 대표자(성명) : 전누리 </li>\r\n");
      out.write("\t\t\t\t<li class=\"footli2\"> 개인정보보호책임자 : 김소현(김소현@naver.com)</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"footText2\">\r\n");
      out.write("\t\t\t<ul id=\"footUl3\">\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 사업자등록번호 : <strong>111-22-333333</strong></li>\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 통신판매번호 : 2019-디아망-1234 </li>\r\n");
      out.write("\t\t\t\t<li class=\"footli3\"> 주소 : 서울특별시 종로구 율곡로10길 105 4층 중앙HTA</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
