/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-11-18 16:59:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.project.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.MemberVO;
import java.util.ArrayList;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.MemberVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

   
    	//String homeURL = "http://192.168.0.4:8080/edgeliving/project";
    	String homeURL = "/edgeliving/project";
    	//String homeURL = "http://192.168.0.4:8080/edgeliving/project";
    	String WebURL = "/edgeliving";
    
    
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t\t<div class=\"header1\" >\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL);
      out.write("/index.jsp\"><img src=\"");
      out.print(WebURL );
      out.write("/semiImages/logo.png\" alt=\"logo.png\"  id=\"mainlogo\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header1\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<strong>인기검색어</strong> <a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=자크라디\" class=\"search_a\">자크라디</a> &nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=임페리얼\" class=\"search_a\">임페리얼 포셀린</a> &nbsp; \r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp?search=보니타하우스\"\tclass=\"search_a\">보니타하우스</a> &nbsp;\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(homeURL );
      out.write("/product/prodlist_search.jsp\" id=\"search_form\" name=\"search_frm\" onsubmit=\"return checkSearch()\">\r\n");
      out.write("\t\t\t \t\t<input type=\"text\" value=\"\" name=\"search\" size=\"40\" id=\"header_search_text\"/>\r\n");
      out.write("\t\t\t \t\t<input type=\"submit\" value=\"검색\" />\r\n");
      out.write("\t\t\t \t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checkSearch(){\r\n");
      out.write("\t\t\tif(search_frm.search.value == \"\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t    alert(\"값을 입력해 주세요.\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t    search_frm.search.focus();\r\n");
      out.write("\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t  }else{\r\n");
      out.write("\t\t\t\t  return true;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t  \r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t");


		Object obj = session.getAttribute("vo");
		
		MemberVO mVO = (MemberVO)obj;
		//
		if(obj == null){
			
		 
		
		
      out.write("\r\n");
      out.write("\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">로그인</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/member/register.jsp\" class=\"header_a2\">회원가입</a> <a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/member/login.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");

		}else{
			
			if(mVO.getAuthority() < 99){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/logout.jsp\" class=\"header_a2\">로그아웃</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/myPage/myPage.jsp\"  class=\"header_a2\">마이페이지</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/mainpage/viewcart.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/checkout/orderlist.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

				
			}else{
				
      out.write("\r\n");
      out.write("\t\t\t<div class=\"header1\" id=\"topAtag\" >\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/member/logout.jsp\" class=\"header_a2\">로그아웃</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/myPage/myPage.jsp\"  class=\"header_a2\">마이페이지</a>\r\n");
      out.write("\t\t\t <a href=\"");
      out.print(homeURL );
      out.write("/mainpage/viewcart.jsp\" class=\"header_a2\">장바구니</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/checkout/orderlist.jsp\" class=\"header_a2\">주문조회</a> <a href=\"");
      out.print(homeURL );
      out.write("/board/customer_center.jsp\" class=\"header_a2\">고객센터</a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(homeURL );
      out.write("/admin/main.jsp\" class=\"header_a2\">관리자페이지</a>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t");

			}
		}
		
      out.write("\r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t\t\t<ul id=\"topMenu\">\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=0\" class=\"menu\" id=\"allCategory\">전체상품</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=1\" class=\"menu\" id=\"newProd\">신상품</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/product/prodlist.jsp?cate_no=2\" class=\"menu\" id=\"best50\">베스트40</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/brand/brand.jsp\" class=\"menu\" id=\"brand\">브랜드</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/edgeliving/project/board/review.jsp\" class=\"menu\" id =\"review\">생생후기</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"contents\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
